const TRANSLATIONS = {
  it: {
  reviews_desc: "Sei stato con leggero? Puoi lasciare una recensione cliccando al link qui sotto! Grazie!",
  review_florence_name: "Florence Kollie",
  review_florence_text: "Riccardo è una guida esperta, discreta ma calorosa e familiare come un vecchio amico. Ti farà sentire come un locale che vive il sogno italiano per un giorno.",
  review_simone_name: "Simone",
  review_simone_text: "La competenza e l’attenzione di Riccardo ci hanno garantito un’esperienza sicura e autentica, davvero affascinante. Consigliatissimo per chi cerca una giornata memorabile in mare!",
  review_giulia_name: "Giulia",
  review_giulia_text: "Un’esperienza che resta nel cuore! Riccardo ha reso tutto semplice e piacevole, con professionalità e attenzione ai dettagli. La giornata è volata tra panorami mozzafiato, momenti autentici e un’atmosfera davvero speciale. Da non perdere per chi cerca un’avventura indimenticabile!",
  all_inclusive: "All-Inclusive",
  all_inclusive_desc: "A bordo troverai tutti i comfort necessari. Viaggia leggero: nessuno stress nel riempire le borse, pensiamo a tutto noi!",
  photo_souvenir: "Foto Ricordo",
  amenities: "Comfort a bordo",
  towels_snacks: "Teli e snack freschi",
  snorkeling_gear: "Attrezzatura snorkeling",
  full_face_masks: "Maschere full face (L)",
  // Booking
  contact_us: "Contattaci!",
  footer_copyright: "© 2025 Leggero Tours",
  footer_credit: "Creato con cura da Riccardo e sviluppato da <a href=\"https://www.linkedin.com/in/francescolimosani/\" style=\"font-weight: 600;\">Francesco Limosani</a>",
    gourmet_desc: "Una magica crociera serale con cena gourmet, vini pregiati e il miglior tramonto sul lago.",
  stella_maris_desc: "Una tradizione dal 1400, di buon auspicio ai pescatori, tra processioni in mare e migliaia di lumini che accendono la notte.",
  rainbow_tour_desc: "Esplora luoghi selvaggi e baie segrete. Da Punta Chiappa a Portofino, passando per Paraggi e San Fruttuoso.",
  gourmet_sunset_desc: "Goditi un ricco aperitivo ligure in rada a Boccadasse, al tramonto. Buon cibo, cieli stellati e delfini che danzano!",
    choose_option: "Scegli un opzione per scoprire la disponibilità",
    experience: "Esperienza",
    rainbow_tour: "Rainbow Tour",
    people: "Persone",
    people_count: "6",
    halfday_morning: "Mezza giornata (Mattina)",
    halfday_morning_time: "7:00 - 14:00",
    halfday_afternoon: "Mezza giornata (Pomeriggio)",
    halfday_afternoon_time: "14:30 - 18:00",
    fullday: "Giornata intera",
    fullday_time: "7:00 - 23:00",
    fullday_desc: "Goditi una giornata di relax che termina con un tramonto mozzafiato e un ricco aperitivo italiano.",
    discount: "40% SCONTO",
    continue: "Continua",
    tour_amazing: "Il tuo tour sembra fantastico!",
    date: "Data",
    slot: "Fascia oraria",
    group_type: "Tipo gruppo",
    combo: "Combinazione",
    final_price: "Prezzo finale",
    your_data: "I tuoi dati",
    name: "Nome <span class='required-star'>*</span>",
    surname: "Cognome <span class='required-star'>*</span>",
    email: "Email <span class='required-star'>*</span>",
    confirm_email: "Conferma Email <span class='required-star'>*</span>",
    phone: "Telefono <span class='required-star'>*</span>",
    phone_placeholder: "Numero di telefono",
    notes: "Note",
    notes_placeholder: "Eventuali note...",
    back: "Indietro",
    book: "Prenota la tua esperienza",
    // Index
    live_gulf: "Vivi il golfo Ligure!",
    enjoy_peace: "Goditi la pace di un tour privato o condividi l’esperienza con persone da tutto il mondo: il viaggio parte dal Porto Antico di Genova, ma il ricordo resta con te.",
    the_experiences: "Le esperienze",
    customize_experience: "Personalizza la tua esperienza secondo le tue esigenze!",
    main: "Principali",
    special: "Speciali",
    price_1300: "1300 € a gruppo",
    price_350: "350 € a gruppo",
    fuel_included: "Carburante Incluso",
    no_surprise: "Nessuna sorpresa extra",
    photo: "Foto Ricordo",
    cheese: "Cheese!",
    water_sports: "Sport Acquatici",
    lets_go: "Andiamo!",
    pet_friendly: "Pet Friendly",
    bring_them: "Portali con te!",
    accessible: "Accessibile Disabili",
    no_one_left: "Nessuno resta indietro",
    equipment: "Dotazioni",
    all_essentials: "Tutto l’essenziale + extra!",
    snacks: "Snack & Bevande",
    we_like_full: "Ci piace la pancia piena",
    flexible: "Flessibile",
    change_plans: "Cambia piani facilmente",
    music: "Musica",
    sure: "Certo",
    snorkeling: "Attrezzatura Snorkeling",
    full_face: "Maschere full face (L)",
    safety: "Sicurezza",
    first_of_all: "Prima di tutto",
    cancellation_policy_link: "Politica di cancellazione",
    ended: "Terminato",
    contact_button: "Contattaci",
    all_day: "Tutto il giorno",
    sunset: "Al tramonto",
    leave_review: "Lascia una review",
    // Cancellation
    cancellation_policy_title: "Politica di Cancellazione",
    cancellation_policy_desc: "Qui trovi le condizioni in caso di rinuncia alla prenotazione o maltempo.",
    in_case_of_cancellation: "In caso di cancellazione",
    cancel_15: "<strong>Fino a 15 giorni prima:</strong> rimborso completo del deposito.",
    cancel_7: "<strong>Fino a 7 giorni prima:</strong> rimborso del 50% del deposito.",
    cancel_0: "<strong>Negli ultimi 7 giorni:</strong> nessun rimborso del deposito.",
    change_date: "Siamo sempre disponibili a spostare la data, compatibilmente con la disponibilità.",
    in_case_of_bad_weather: "In caso di maltempo",
    bad_weather_desc: "Se il mare presenta onde di <strong>1.5 metri o più</strong>, non sarà possibile uscire in barca. In questo caso:",
    try_new_date: "Proveremo a trovare insieme una nuova data disponibile.",
    refund: "Se non fosse possibile, ti verrà restituito l’intero importo."
  },
  en: {
  reviews_desc: "Have you sailed with Leggero? You can leave a review by clicking the link below! Thank you!",
  review_florence_name: "Florence Kollie",
  review_florence_text: "Riccardo is an experienced water guide, unimposing, discreet but warm and familiar like an old friend you are reuniting with. He will make you feel like a local for the day living the Italian dream.",
  review_simone_name: "Simone",
  review_simone_text: "Riccardo’s expertise and attention to detail ensured us a very safe, seamless experience that felt both authentic and truly charming. Highly recommended for anyone seeking a memorable day at sea!",
  review_giulia_name: "Giulia",
  review_giulia_text: "An experience that stays in your heart! Riccardo made everything simple and pleasant, with professionalism and attention to detail. The day flew by among breathtaking views, authentic moments and a truly special atmosphere. Not to be missed for those seeking an unforgettable adventure!",
  all_inclusive: "All-Inclusive",
  all_inclusive_desc: "On board you'll find all the amenities you need. Travel light: no stress packing bags, we take care of everything!",
  photo_souvenir: "Souvenir Photo",
  amenities: "Amenities on board",
  towels_snacks: "Towels and fresh snacks",
  snorkeling_gear: "Snorkeling gear",
  full_face_masks: "Full face masks (L)",
  // Booking
  contact_us: "Contact us!",
  footer_copyright: "© 2025 Leggero Tours",
  footer_credit: "Created with care by Riccardo and developed by <a href=\"https://www.linkedin.com/in/francescolimosani/\" style=\"font-weight: 600;\">Francesco Limosani</a>",
    gourmet_desc: "A magical evening cruise with gourmet dinner, fine wines, and the best sunset on the lake.",
  stella_maris_desc: "A tradition since the 1400s, bringing good luck to fishermen, with sea processions and thousands of lanterns lighting up the night.",
  rainbow_tour_desc: "Explore wild places and secret bays. From Punta Chiappa to Portofino, passing through Paraggi and San Fruttuoso.",
  gourmet_sunset_desc: "Enjoy a rich Ligurian aperitif at anchor in Boccadasse, at sunset. Good food, starry skies and dancing dolphins!",
    choose_option: "Choose an option to check availability",
    experience: "Experience",
    rainbow_tour: "Rainbow Tour",
    people: "People",
    people_count: "6",
    halfday_morning: "Half Day (Morning)",
    halfday_morning_time: "7:00AM - 2:00 PM",
    halfday_afternoon: "Half Day (Afternoon)",
    halfday_afternoon_time: "2:30PM - 6:00 PM",
    fullday: "Full Day",
    fullday_time: "7:00AM - 11:00 PM",
    fullday_desc: "Enjoy a full day of relaxation, ending with a breathtaking sunset and a rich Italian aperitivo.",
    discount: "40% OFF",
    continue: "Continue",
    tour_amazing: "Your Tour looks amazing!",
    date: "Date",
    slot: "Slot",
    group_type: "Group Type",
    combo: "Combo",
    final_price: "Final Price",
    your_data: "Your Data",
    name: "Name <span class='required-star'>*</span>",
    surname: "Surname <span class='required-star'>*</span>",
    email: "Email <span class='required-star'>*</span>",
    confirm_email: "Confirm Email <span class='required-star'>*</span>",
    phone: "Phone <span class='required-star'>*</span>",
    phone_placeholder: "Phone number",
    notes: "Notes",
    notes_placeholder: "Any notes...",
    back: "Back",
    book: "Book your experience",
    // Index
    live_gulf: "Live the Ligurian Gulf!",
    enjoy_peace: "Enjoy the peace of a private tour or share the experience with people from all over the world: the journey starts from Genoa's Old Port, but the memory stays with you.",
    the_experiences: "The experiences",
    customize_experience: "Customize your experience according to your needs!<br>Or contact us for an exclusive tour!",
    main: "Main",
    special: "Special",
    price_1300: "1300 € per group",
    price_350: "350 € per group",
    fuel_included: "Fuel Included",
    no_surprise: "No extra surprises",
    photo: "Souvenir Photo",
    cheese: "Cheese!",
    water_sports: "Water Sports",
    lets_go: "Let's go!",
    pet_friendly: "Pet Friendly",
    bring_them: "Bring them with you!",
    accessible: "Accessible for Disabled",
    no_one_left: "No one left behind",
    equipment: "Equipment",
    all_essentials: "All essentials + extras!",
    snacks: "Snacks & Drinks",
    we_like_full: "We like full bellies",
    flexible: "Flexible",
    change_plans: "Change plans easily",
    music: "Music",
    sure: "Sure",
    snorkeling: "Snorkeling Equipment",
    full_face: "Full face masks (L)",
    safety: "Safety",
    first_of_all: "First of all",
    cancellation_policy_link: "Cancellation Policy",
    ended: "Ended",
    contact_button: "Contact us",
    all_day: "All day",
    sunset: "At sunset",
    leave_review: "Leave a review",
    // Cancellation
    cancellation_policy_title: "Cancellation Policy",
    cancellation_policy_desc: "Here you find the conditions in case of booking cancellation or bad weather.",
    in_case_of_cancellation: "In case of cancellation",
    cancel_15: "<strong>Up to 15 days before:</strong> full refund of the deposit.",
    cancel_7: "<strong>Up to 7 days before:</strong> 50% refund of the deposit.",
    cancel_0: "<strong>In the last 7 days:</strong> no refund of the deposit.",
    change_date: "We are always available to reschedule, subject to availability.",
    in_case_of_bad_weather: "In case of bad weather",
    bad_weather_desc: "If the sea has waves of <strong>1.5 meters or more</strong>, it will not be possible to go out by boat. In this case:",
    try_new_date: "We will try to find a new available date together.",
    refund: "If not possible, you will be refunded the full amount."
  },
  de: {
  reviews_desc: "Warst du mit Leggero unterwegs? Du kannst unten eine Bewertung hinterlassen! Danke!",
  review_florence_name: "Florence Kollie",
  review_florence_text: "Riccardo ist ein erfahrener Wasserführer, unaufdringlich, diskret, aber herzlich und vertraut wie ein alter Freund. Er lässt Sie sich wie ein Einheimischer fühlen, der den italienischen Traum lebt.",
  review_simone_name: "Simone",
  review_simone_text: "Riccardos Fachwissen und Aufmerksamkeit sorgten für ein sehr sicheres, authentisches und charmantes Erlebnis. Sehr zu empfehlen für alle, die einen unvergesslichen Tag auf See suchen!",
  review_giulia_name: "Giulia",
  review_giulia_text: "Ein Erlebnis, das im Herzen bleibt! Riccardo machte alles einfach und angenehm, mit Professionalität und Liebe zum Detail. Der Tag verging wie im Flug zwischen atemberaubenden Aussichten, authentischen Momenten und einer wirklich besonderen Atmosphäre. Nicht zu verpassen für alle, die ein unvergessliches Abenteuer suchen!",
  all_inclusive: "All-Inclusive",
  all_inclusive_desc: "An Bord finden Sie alle notwendigen Annehmlichkeiten. Reisen Sie leicht: kein Stress beim Packen, wir kümmern uns um alles!",
  photo_souvenir: "Erinnerungsfoto",
  amenities: "Komfort an Bord",
  towels_snacks: "Handtücher und frische Snacks",
  snorkeling_gear: "Schnorchelausrüstung",
  full_face_masks: "Vollgesichtsmasken (L)",
  // Booking
  contact_us: "Kontakt!",
  footer_copyright: "© 2025 Leggero Tours",
  footer_credit: "Mit Liebe erstellt von Riccardo und entwickelt von <a href=\"https://www.linkedin.com/in/francescolimosani/\" style=\"font-weight: 600;\">Francesco Limosani</a>",
    gourmet_desc: "Eine magische Abendkreuzfahrt mit Gourmet-Dinner, erlesenen Weinen und dem schönsten Sonnenuntergang am See.",
  stella_maris_desc: "Eine Tradition seit dem 15. Jahrhundert, Glücksbringer für Fischer, mit Prozessionen auf dem Meer und tausenden Lichtern in der Nacht.",
  rainbow_tour_desc: "Entdecken Sie wilde Orte und geheime Buchten. Von Punta Chiappa bis Portofino, über Paraggi und San Fruttuoso.",
  gourmet_sunset_desc: "Genießen Sie einen reichhaltigen ligurischen Aperitif vor Anker in Boccadasse, bei Sonnenuntergang. Gutes Essen, Sternenhimmel und tanzende Delfine!",
    choose_option: "Wähle eine Option, um die Verfügbarkeit zu prüfen",
    experience: "Erlebnis",
    rainbow_tour: "Rainbow Tour",
    people: "Personen",
    people_count: "6",
    halfday_morning: "Halber Tag (Morgen)",
    halfday_morning_time: "7:00 - 14:00",
    halfday_afternoon: "Halber Tag (Nachmittag)",
    halfday_afternoon_time: "14:30 - 18:00",
    fullday: "Ganzer Tag",
    fullday_time: "7:00 - 23:00",
    fullday_desc: "Genießen Sie einen entspannten Tag mit atemberaubendem Sonnenuntergang und italienischem Aperitif.",
    discount: "40% RABATT",
    continue: "Weiter",
    tour_amazing: "Ihre Tour sieht fantastisch aus!",
    date: "Datum",
    slot: "Zeitfenster",
    group_type: "Gruppentyp",
    combo: "Kombination",
    final_price: "Endpreis",
    your_data: "Ihre Daten",
    name: "Name <span class='required-star'>*</span>",
    surname: "Nachname <span class='required-star'>*</span>",
    email: "E-Mail <span class='required-star'>*</span>",
    confirm_email: "E-Mail bestätigen <span class='required-star'>*</span>",
    phone: "Telefon <span class='required-star'>*</span>",
    phone_placeholder: "Telefonnummer",
    notes: "Notizen",
    notes_placeholder: "Weitere Hinweise...",
    back: "Zurück",
    book: "Erlebnis buchen",
    // Index
    live_gulf: "Erleben Sie den Golf von Ligurien!",
    enjoy_peace: "Genießen Sie die Ruhe einer privaten Tour oder teilen Sie das Erlebnis mit Menschen aus aller Welt: Die Reise beginnt im Alten Hafen von Genua, aber die Erinnerung bleibt.",
    the_experiences: "Die Erlebnisse",
    customize_experience: "Passen Sie Ihr Erlebnis an Ihre Wünsche an!<br>Oder kontaktieren Sie uns für eine exklusive Tour!",
    main: "Haupttouren",
    special: "Spezialtouren",
    price_1300: "1300 € pro Gruppe",
    price_350: "350 € pro Gruppe",
    fuel_included: "Kraftstoff inklusive",
    no_surprise: "Keine versteckten Kosten",
    photo: "Erinnerungsfoto",
    cheese: "Cheese!",
    water_sports: "Wassersport",
    lets_go: "Los geht's!",
    pet_friendly: "Haustierfreundlich",
    bring_them: "Bringen Sie sie mit!",
    accessible: "Barrierefrei",
    no_one_left: "Niemand bleibt zurück",
    equipment: "Ausstattung",
    all_essentials: "Alles Notwendige + Extras!",
    snacks: "Snacks & Getränke",
    we_like_full: "Wir mögen volle Bäuche",
    flexible: "Flexibel",
    change_plans: "Pläne einfach ändern",
    music: "Musik",
    sure: "Natürlich",
    snorkeling: "Schnorchelausrüstung",
    full_face: "Vollgesichtsmasken (L)",
    safety: "Sicherheit",
    first_of_all: "An erster Stelle",
    cancellation_policy_link: "Stornierungsbedingungen",
    ended: "Beendet",
    contact_button: "Kontakt",
    all_day: "Den ganzen Tag",
    sunset: "Bei Sonnenuntergang",
    leave_review: "Bewertung abgeben",
    // Cancellation
    cancellation_policy_title: "Stornierungsbedingungen",
    cancellation_policy_desc: "Hier finden Sie die Bedingungen bei Stornierung oder schlechtem Wetter.",
    in_case_of_cancellation: "Im Falle einer Stornierung",
    cancel_15: "<strong>Bis 15 Tage vorher:</strong> volle Rückerstattung der Anzahlung.",
    cancel_7: "<strong>Bis 7 Tage vorher:</strong> 50% Rückerstattung der Anzahlung.",
    cancel_0: "<strong>In den letzten 7 Tagen:</strong> keine Rückerstattung der Anzahlung.",
    change_date: "Wir sind immer bereit, das Datum nach Verfügbarkeit zu ändern.",
    in_case_of_bad_weather: "Bei schlechtem Wetter",
    bad_weather_desc: "Wenn das Meer Wellen von <strong>1,5 Metern oder mehr</strong> hat, ist eine Ausfahrt nicht möglich. In diesem Fall:",
    try_new_date: "Wir versuchen gemeinsam ein neues Datum zu finden.",
    refund: "Falls nicht möglich, erhalten Sie den vollen Betrag zurück."
  },
  fr: {
  reviews_desc: "Vous avez navigué avec Leggero ? Vous pouvez laisser un avis en cliquant sur le lien ci-dessous ! Merci !",
  review_florence_name: "Florence Kollie",
  review_florence_text: "Riccardo est un guide expérimenté, discret mais chaleureux et familier comme un vieil ami. Il vous fera sentir comme un local vivant le rêve italien le temps d'une journée.",
  review_simone_name: "Simone",
  review_simone_text: "L’expertise et l’attention de Riccardo nous ont assuré une expérience très sûre et authentique, vraiment charmante. Recommandé à tous ceux qui recherchent une journée mémorable en mer !",
  review_giulia_name: "Giulia",
  review_giulia_text: "Une expérience qui reste dans le cœur ! Riccardo a rendu tout simple et agréable, avec professionnalisme et attention aux détails. La journée a filé entre panoramas époustouflants, moments authentiques et une atmosphère vraiment spéciale. À ne pas manquer pour ceux qui cherchent une aventure inoubliable !",
  all_inclusive: "All-Inclusive",
  all_inclusive_desc: "À bord, vous trouverez tout le confort nécessaire. Voyagez léger : pas de stress pour remplir les sacs, on s'occupe de tout !",
  photo_souvenir: "Photo souvenir",
  amenities: "Confort à bord",
  towels_snacks: "Serviettes et snacks frais",
  snorkeling_gear: "Équipement de snorkeling",
  full_face_masks: "Masques intégraux (L)",
  gourmet_desc: "Une croisière du soir magique avec dîner gastronomique, vins fins et le plus beau coucher de soleil sur le lac.",
  contact_us: "Contactez-nous!",
  footer_copyright: "© 2025 Leggero Tours",
  footer_credit: "Créé avec soin par Riccardo et développé par <a href=\"https://www.linkedin.com/in/francescolimosani/\" style=\"font-weight: 600;\">Francesco Limosani</a>",
  stella_maris_desc: "Une tradition depuis 1400, porte-bonheur pour les pêcheurs, entre processions en mer et milliers de lanternes qui illuminent la nuit.",
  rainbow_tour_desc: "Explorez des lieux sauvages et des baies secrètes. De Punta Chiappa à Portofino, en passant par Paraggi et San Fruttuoso.",
  gourmet_sunset_desc: "Profitez d’un riche apéritif ligure à l’ancre à Boccadasse, au coucher du soleil. Bonne cuisine, ciel étoilé et dauphins dansants!",
    choose_option: "Choisissez une option pour vérifier la disponibilité",
    experience: "Expérience",
    rainbow_tour: "Rainbow Tour",
    people: "Personnes",
    people_count: "6",
    halfday_morning: "Demi-journée (matin)",
    halfday_morning_time: "7h00 - 14h00",
    halfday_afternoon: "Demi-journée (après-midi)",
    halfday_afternoon_time: "14h30 - 18h00",
    fullday: "Journée complète",
    fullday_time: "7h00 - 23h00",
    fullday_desc: "Profitez d'une journée de détente, d'un coucher de soleil et d'un apéritif italien.",
    discount: "40% RÉDUCTION",
    continue: "Continuer",
    tour_amazing: "Votre tour est incroyable !",
    date: "Date",
    slot: "Créneau",
    group_type: "Type de groupe",
    combo: "Combo",
    final_price: "Prix final",
    your_data: "Vos informations",
    name: "Prénom <span class='required-star'>*</span>",
    surname: "Nom <span class='required-star'>*</span>",
    email: "E-mail <span class='required-star'>*</span>",
    confirm_email: "Confirmer l'e-mail <span class='required-star'>*</span>",
    phone: "Téléphone <span class='required-star'>*</span>",
    phone_placeholder: "Numéro de téléphone",
    notes: "Notes",
    notes_placeholder: "Notes éventuelles...",
    back: "Retour",
    book: "Réserver votre expérience",
    live_gulf: "Vivez le golfe ligure !",
    enjoy_peace: "Profitez de la tranquillité d'une visite privée ou partagez l'expérience avec des personnes du monde entier : le voyage commence au Vieux-Port de Gênes, mais le souvenir reste.",
    the_experiences: "Les expériences",
    customize_experience: "Personnalisez votre expérience selon vos besoins !<br>Ou contactez-nous pour une visite exclusive !",
    main: "Principales",
    special: "Spéciales",
    price_1300: "1300 € par groupe",
    price_350: "350 € par groupe",
    fuel_included: "Carburant inclus",
    no_surprise: "Aucune surprise",
    photo: "Photo souvenir",
    cheese: "Cheese!",
    water_sports: "Sports nautiques",
    lets_go: "Allons-y !",
    pet_friendly: "Animaux acceptés",
    bring_them: "Emmenez-les avec vous !",
    accessible: "Accessible PMR",
    no_one_left: "Personne n'est laissé de côté",
    equipment: "Équipement",
    all_essentials: "Tout le nécessaire + extra !",
    snacks: "Snacks et boissons",
    we_like_full: "On aime avoir le ventre plein",
    flexible: "Flexible",
    change_plans: "Changez de plans facilement",
    music: "Musique",
    sure: "Bien sûr",
    snorkeling: "Équipement de snorkeling",
    full_face: "Masques intégraux (L)",
    safety: "Sécurité",
    first_of_all: "Avant tout",
    cancellation_policy_link: "Politique d'annulation",
    ended: "Terminé",
    contact_button: "Contactez-nous",
    all_day: "Toute la journée",
    sunset: "Au coucher du soleil",
    leave_review: "Laisser un avis",
    // Cancellation
    cancellation_policy_title: "Politique d'annulation",
    cancellation_policy_desc: "Vous trouverez ici les conditions en cas d'annulation ou de mauvais temps.",
    in_case_of_cancellation: "En cas d'annulation",
    cancel_15: "<strong>Jusqu'à 15 jours avant :</strong> remboursement total de l'acompte.",
    cancel_7: "<strong>Jusqu'à 7 jours avant :</strong> remboursement de 50% de l'acompte.",
    cancel_0: "<strong>Dans les 7 derniers jours :</strong> aucun remboursement de l'acompte.",
    change_date: "Nous sommes toujours disponibles pour changer la date, selon disponibilité.",
    in_case_of_bad_weather: "En cas de mauvais temps",
    bad_weather_desc: "Si la mer a des vagues de <strong>1,5 mètre ou plus</strong>, il ne sera pas possible de sortir en bateau. Dans ce cas :",
    try_new_date: "Nous essaierons de trouver une nouvelle date ensemble.",
    refund: "Si ce n'est pas possible, vous serez remboursé intégralement."
  },
  es: {
  reviews_desc: "¿Has navegado con Leggero? Puedes dejar una reseña haciendo clic en el enlace de abajo. ¡Gracias!",
  review_florence_name: "Florence Kollie",
  review_florence_text: "Riccardo es un guía experimentado, discreto pero cálido y familiar como un viejo amigo. Te hará sentir como un local viviendo el sueño italiano por un día.",
  review_simone_name: "Simone",
  review_simone_text: "La experiencia y atención de Riccardo nos aseguraron una experiencia muy segura y auténtica, realmente encantadora. ¡Muy recomendado para quien busque un día memorable en el mar!",
  review_giulia_name: "Giulia",
  review_giulia_text: "¡Una experiencia que queda en el corazón! Riccardo hizo todo fácil y agradable, con profesionalidad y atención al detalle. El día pasó volando entre paisajes impresionantes, momentos auténticos y un ambiente realmente especial. ¡Imperdible para quien busque una aventura inolvidable!",
  all_inclusive: "All-Inclusive",
  all_inclusive_desc: "A bordo encontrarás todas las comodidades necesarias. ¡Viaja ligero: sin estrés llenando las bolsas, nosotros nos encargamos de todo!",
  photo_souvenir: "Foto recuerdo",
  amenities: "Comodidades a bordo",
  towels_snacks: "Toallas y snacks frescos",
  snorkeling_gear: "Equipo de snorkel",
  full_face_masks: "Máscaras integrales (L)",
  gourmet_desc: "Un crucero nocturno mágico con cena gourmet, vinos selectos y la mejor puesta de sol del lago.",
  contact_us: "¡Contáctanos!",
  footer_copyright: "© 2025 Leggero Tours",
  footer_credit: "Creado con cariño por Riccardo y desarrollado por <a href=\"https://www.linkedin.com/in/francescolimosani/\" style=\"font-weight: 600;\">Francesco Limosani</a>",
  stella_maris_desc: "Una tradición desde 1400, de buena suerte para los pescadores, entre procesiones en el mar y miles de farolillos que iluminan la noche.",
  rainbow_tour_desc: "Explora lugares salvajes y bahías secretas. De Punta Chiappa a Portofino, pasando por Paraggi y San Fruttuoso.",
  gourmet_sunset_desc: "Disfruta de un rico aperitivo ligur en Boccadasse, al atardecer. ¡Buena comida, cielos estrellados y delfines bailando!",
    choose_option: "Elige una opción para comprobar la disponibilidad",
    experience: "Experiencia",
    rainbow_tour: "Rainbow Tour",
    people: "Personas",
    people_count: "6",
    halfday_morning: "Medio día (mañana)",
    halfday_morning_time: "7:00 - 14:00",
    halfday_afternoon: "Medio día (tarde)",
    halfday_afternoon_time: "14:30 - 18:00",
    fullday: "Día completo",
    fullday_time: "7:00 - 23:00",
    fullday_desc: "Disfruta de un día de relax, con una puesta de sol y un aperitivo italiano.",
    discount: "40% DESCUENTO",
    continue: "Continuar",
    tour_amazing: "¡Tu tour es increíble!",
    date: "Fecha",
    slot: "Horario",
    group_type: "Tipo de grupo",
    combo: "Combo",
    final_price: "Precio final",
    your_data: "Tus datos",
    name: "Nombre <span class='required-star'>*</span>",
    surname: "Apellido <span class='required-star'>*</span>",
    email: "Correo electrónico <span class='required-star'>*</span>",
    confirm_email: "Confirmar correo <span class='required-star'>*</span>",
    phone: "Teléfono <span class='required-star'>*</span>",
    phone_placeholder: "Número de teléfono",
    notes: "Notas",
    notes_placeholder: "Notas adicionales...",
    back: "Atrás",
    book: "Reserva tu experiencia",
    live_gulf: "¡Vive el golfo de Liguria!",
    enjoy_peace: "Disfruta de la tranquilidad de un tour privado o comparte la experiencia con personas de todo el mundo: el viaje comienza en el Puerto Antiguo de Génova, pero el recuerdo permanece.",
    the_experiences: "Las experiencias",
    customize_experience: "¡Personaliza tu experiencia según tus necesidades!<br>O contáctanos para un tour exclusivo!",
    main: "Principales",
    special: "Especiales",
    price_1300: "1300 € por grupo",
    price_350: "350 € por grupo",
    fuel_included: "Combustible incluido",
    no_surprise: "Sin sorpresas extra",
    photo: "Foto recuerdo",
    cheese: "¡Cheese!",
    water_sports: "Deportes acuáticos",
    lets_go: "¡Vamos!",
    pet_friendly: "Pet Friendly",
    bring_them: "¡Tráelos contigo!",
    accessible: "Accesible",
    no_one_left: "Nadie se queda atrás",
    equipment: "Equipamiento",
    all_essentials: "Todo lo esencial + extras!",
    snacks: "Snacks y bebidas",
    we_like_full: "Nos gusta la barriga llena",
    flexible: "Flexible",
    change_plans: "Cambia de planes fácilmente",
    music: "Música",
    sure: "Por supuesto",
    snorkeling: "Equipo de snorkel",
    full_face: "Máscaras integrales (L)",
    safety: "Seguridad",
    first_of_all: "Ante todo",
    cancellation_policy_link: "Política de cancelación",
    ended: "Finalizado",
    contact_button: "¡Contáctanos!",
    all_day: "Todo el día",
    sunset: "Al atardecer",
    leave_review: "¡Deja una reseña!",
    // Cancellation
    cancellation_policy_title: "Política de cancelación",
    cancellation_policy_desc: "Aquí encuentras las condiciones en caso de cancelación o mal tiempo.",
    in_case_of_cancellation: "En caso de cancelación",
    cancel_15: "<strong>Hasta 15 días antes:</strong> reembolso total del depósito.",
    cancel_7: "<strong>Hasta 7 días antes:</strong> reembolso del 50% del depósito.",
    cancel_0: "<strong>En los últimos 7 días:</strong> sin reembolso del depósito.",
    change_date: "Siempre estamos disponibles para cambiar la fecha, según disponibilidad.",
    in_case_of_bad_weather: "En caso de mal tiempo",
    bad_weather_desc: "Si el mar tiene olas de <strong>1,5 metros o más</strong>, no será posible salir en barco. En este caso:",
    try_new_date: "Intentaremos encontrar juntos una nueva fecha disponible.",
    refund: "Si no es posible, se te devolverá el importe total."
  },
  pl: {
  reviews_desc: "Byłeś z Leggero? Możesz zostawić recenzję, klikając poniższy link! Dziękujemy!",
  review_florence_name: "Florence Kollie",
  review_florence_text: "Riccardo to doświadczony przewodnik wodny, nienachalny, dyskretny, ale ciepły i swojski jak stary przyjaciel. Sprawi, że poczujesz się jak miejscowy, przeżywając włoski sen przez jeden dzień.",
  review_simone_name: "Simone",
  review_simone_text: "Doświadczenie i dbałość Riccardo zapewniły nam bardzo bezpieczne, autentyczne i urocze przeżycie. Polecam każdemu, kto szuka niezapomnianego dnia na morzu!",
  review_giulia_name: "Giulia",
  review_giulia_text: "Doświadczenie, które zostaje w sercu! Riccardo sprawił, że wszystko było proste i przyjemne, z profesjonalizmem i dbałością o szczegóły. Dzień minął wśród zapierających dech widoków, autentycznych chwil i naprawdę wyjątkowej atmosfery. Nie do przegapienia dla szukających niezapomnianej przygody!",
  all_inclusive: "All-Inclusive",
  all_inclusive_desc: "Na pokładzie znajdziesz wszystkie potrzebne udogodnienia. Podróżuj lekko: bez stresu z pakowaniem, my o wszystko zadbamy!",
  photo_souvenir: "Zdjęcie pamiątkowe",
  amenities: "Komfort na pokładzie",
  towels_snacks: "Ręczniki i świeże przekąski",
  snorkeling_gear: "Sprzęt do nurkowania",
  full_face_masks: "Maski pełnotwarzowe (L)",
  gourmet_desc: "Magiczny wieczorny rejs z kolacją gourmet, wybornymi winami i najpiękniejszym zachodem słońca nad jeziorem.",
  contact_us: "Skontaktuj się!",
  footer_copyright: "© 2025 Leggero Tours",
  footer_credit: "Stworzone z troską przez Riccardo, rozwinięte przez <a href=\"https://www.linkedin.com/in/francescolimosani/\" style=\"font-weight: 600;\">Francesco Limosani</a>",
  stella_maris_desc: "Tradycja od XV wieku, szczęście dla rybaków, procesje morskie i tysiące świateł rozświetlających noc.",
  rainbow_tour_desc: "Odkryj dzikie miejsca i sekretne zatoki. Od Punta Chiappa do Portofino, przez Paraggi i San Fruttuoso.",
  gourmet_sunset_desc: "Ciesz się bogatym liguryjskim aperitifem na kotwicy w Boccadasse, o zachodzie słońca. Dobre jedzenie, gwiaździste niebo i tańczące delfiny!",
    choose_option: "Wybierz opcję, aby sprawdzić dostępność",
    experience: "Doświadczenie",
    rainbow_tour: "Rainbow Tour",
    people: "Osoby",
    people_count: "6",
    halfday_morning: "Pół dnia (rano)",
    halfday_morning_time: "7:00 - 14:00",
    halfday_afternoon: "Pół dnia (popołudnie)",
    halfday_afternoon_time: "14:30 - 18:00",
    fullday: "Cały dzień",
    fullday_time: "7:00 - 23:00",
    fullday_desc: "Ciesz się dniem relaksu, zachodem słońca i włoskim aperitifem.",
    discount: "40% ZNIŻKI",
    continue: "Dalej",
    tour_amazing: "Twoja wycieczka wygląda niesamowicie!",
    date: "Data",
    slot: "Godzina",
    group_type: "Typ grupy",
    combo: "Kombinacja",
    final_price: "Cena końcowa",
    your_data: "Twoje dane",
    name: "Imię <span class='required-star'>*</span>",
    surname: "Nazwisko <span class='required-star'>*</span>",
    email: "E-mail <span class='required-star'>*</span>",
    confirm_email: "Potwierdź e-mail <span class='required-star'>*</span>",
    phone: "Telefon <span class='required-star'>*</span>",
    phone_placeholder: "Numer telefonu",
    notes: "Notatki",
    notes_placeholder: "Dodatkowe uwagi...",
    back: "Wstecz",
    book: "Zarezerwuj doświadczenie",
    live_gulf: "Przeżyj Zatokę Liguryjską!",
    enjoy_peace: "Ciesz się spokojem prywatnej wycieczki lub podziel się doświadczeniem z ludźmi z całego świata: podróż zaczyna się w Starym Porcie w Genui, ale wspomnienie zostaje z Tobą.",
    the_experiences: "Doświadczenia",
    customize_experience: "Dostosuj swoje doświadczenie do swoich potrzeb!<br>Lub skontaktuj się z nami po ekskluzywną wycieczkę!",
    main: "Główne",
    special: "Specjalne",
    price_1300: "1300 € za grupę",
    price_350: "350 € za grupę",
    fuel_included: "Paliwo w cenie",
    no_surprise: "Brak ukrytych kosztów",
    photo: "Zdjęcie pamiątkowe",
    cheese: "Cheese!",
    water_sports: "Sporty wodne",
    lets_go: "Jedziemy!",
    pet_friendly: "Przyjazny zwierzętom",
    bring_them: "Zabierz je ze sobą!",
    accessible: "Dostępny dla niepełnosprawnych",
    no_one_left: "Nikt nie zostaje w tyle",
    equipment: "Wyposażenie",
    all_essentials: "Wszystko co potrzebne + dodatki!",
    snacks: "Przekąski i napoje",
    we_like_full: "Lubimy pełne brzuchy",
    flexible: "Elastyczny",
    change_plans: "Łatwa zmiana planów",
    music: "Muzyka",
    sure: "Oczywiście",
    snorkeling: "Sprzęt do nurkowania",
    full_face: "Maski pełnotwarzowe (L)",
    safety: "Bezpieczeństwo",
    first_of_all: "Przede wszystkim",
    cancellation_policy_link: "Polityka anulowania",
    ended: "Zakończone",
    contact_button: "Skontaktuj się!",
    all_day: "Cały dzień",
    sunset: "O zachodzie słońca",
    leave_review: "Zostaw opinię",
    cancellation_policy_title: "Polityka anulowania",
    cancellation_policy_desc: "Tutaj znajdziesz warunki w przypadku anulowania lub złej pogody.",
    in_case_of_cancellation: "W przypadku anulowania",
    cancel_15: "<strong>Do 15 dni przed:</strong> pełny zwrot zaliczki.",
    cancel_7: "<strong>Do 7 dni przed:</strong> zwrot 50% zaliczki.",
    cancel_0: "<strong>W ostatnich 7 dniach:</strong> brak zwrotu zaliczki.",
    change_date: "Zawsze możemy zmienić termin, jeśli są wolne miejsca.",
    in_case_of_bad_weather: "W przypadku złej pogody",
    bad_weather_desc: "Jeśli na morzu są fale o wysokości <strong>1,5 metra lub więcej</strong>, nie będzie można wypłynąć. W takim przypadku:",
    try_new_date: "Postaramy się znaleźć nowy termin.",
    refund: "Jeśli to niemożliwe, otrzymasz pełny zwrot."
  },
ru: {
  reviews_desc: "Вы были с Leggero? Вы можете оставить отзыв, нажав на ссылку ниже! Спасибо!",
  review_florence_name: "Florence Kollie",
  review_florence_text: "Риккардо — опытный гид по воде, ненавязчивый и деликатный, но тёплый и близкий, как старый друг. Он поможет вам почувствовать себя местным жителем, проживающим итальянскую мечту один день.",
  review_simone_name: "Simone",
  review_simone_text: "Профессионализм и внимание Риккардо обеспечили нам очень безопасный, аутентичный и по-настоящему очаровательный опыт. Рекомендуем всем, кто ищет незабываемый день на море!",
  review_giulia_name: "Giulia",
  review_giulia_text: "Опыт, который остаётся в сердце! Риккардо сделал всё просто и приятно, с профессионализмом и вниманием к деталям. День пролетел среди захватывающих видов, искренних моментов и особой атмосферы. Обязательно для тех, кто ищет незабываемое приключение!",
  all_inclusive: "All-Inclusive",
  all_inclusive_desc: "На борту есть всё необходимое. Путешествуйте налегке: никакого стресса с багажом — мы обо всём позаботимся!",
  photo_souvenir: "Фото на память",
  amenities: "Комфорт на борту",
  towels_snacks: "Полотенца и свежие закуски",
  snorkeling_gear: "Снаряжение для сноркелинга",
  full_face_masks: "Полнолицевые маски (L)",
  gourmet_desc: "Волшебный вечерний круиз с изысканным ужином, отличными винами и лучшим закатом на озере.",
  contact_us: "Свяжитесь с нами!",
  footer_copyright: "© 2025 Leggero Tours",
  footer_credit: "Создано с заботой Риккардо, разработано <a href=\"https://www.linkedin.com/in/francescolimosani/\" style=\"font-weight: 600;\">Francesco Limosani</a>",
  stella_maris_desc: "Традиция с XV века на удачу рыбакам: морские процессии и тысячи огней, освещающих ночь.",
  rainbow_tour_desc: "Исследуйте дикие места и секретные бухты. От Пунта Кьяппа до Портофино через Параджи и Сан-Фруттуозо.",
  gourmet_sunset_desc: "Наслаждайтесь богатым лигурийским аперитивом на якоре в Боккадассе на закате. Вкусная еда, звёздное небо и «танцующие» дельфины!",
  choose_option: "Выберите вариант, чтобы проверить доступность",
  experience: "Экскурсия",
  rainbow_tour: "Rainbow Tour",
  people: "Человек",
  people_count: "6",
  halfday_morning: "Полдня (утро)",
  halfday_morning_time: "7:00 - 14:00",
  halfday_afternoon: "Полдня (день)",
  halfday_afternoon_time: "14:30 - 18:00",
  fullday: "Весь день",
  fullday_time: "7:00 - 23:00",
  fullday_desc: "Наслаждайтесь днём отдыха, завершающимся захватывающим закатом и итальянским аперитивом.",
  discount: "СКИДКА 40%",
  continue: "Продолжить",
  tour_amazing: "Ваша экскурсия выглядит потрясающе!",
  date: "Дата",
  slot: "Время",
  group_type: "Тип группы",
  combo: "Комбо",
  final_price: "Итоговая цена",
  your_data: "Ваши данные",
  name: "Имя <span class='required-star'>*</span>",
  surname: "Фамилия <span class='required-star'>*</span>",
  email: "E-mail <span class='required-star'>*</span>",
  confirm_email: "Подтвердите e-mail <span class='required-star'>*</span>",
  phone: "Телефон <span class='required-star'>*</span>",
  phone_placeholder: "Номер телефона",
  notes: "Заметки",
  notes_placeholder: "Дополнительные заметки...",
  back: "Назад",
  book: "Забронировать экскурсию",
  live_gulf: "Откройте для себя Лигурийский залив!",
  enjoy_peace: "Наслаждайтесь спокойствием частной экскурсии или разделите опыт с людьми со всего мира: путешествие начинается в Старом порту Генуи, но воспоминания останутся с вами.",
  the_experiences: "Экскурсии",
  customize_experience: "Настройте свой опыт под себя!<br>Или свяжитесь с нами для эксклюзивного тура!",
  main: "Основные",
  special: "Специальные",
  price_1300: "1300 € за группу",
  price_350: "350 € за группу",
  fuel_included: "Топливо включено",
  no_surprise: "Без скрытых платежей",
  photo: "Фото на память",
  cheese: "Скажи «сыр»!",
  water_sports: "Водные виды спорта",
  lets_go: "Поехали!",
  pet_friendly: "Можно с животными",
  bring_them: "Берите их с собой!",
  accessible: "Доступно для инвалидов",
  no_one_left: "Никто не останется позади",
  equipment: "Оборудование",
  all_essentials: "Всё необходимое + дополнительно!",
  snacks: "Закуски и напитки",
  we_like_full: "Любим быть сытыми",
  flexible: "Гибко",
  change_plans: "Легко изменить планы",
  music: "Музыка",
  sure: "Конечно",
  snorkeling: "Снаряжение для сноркелинга",
  full_face: "Полнолицевые маски (L)",
  safety: "Безопасность",
  first_of_all: "Прежде всего",
  cancellation_policy_link: "Политика отмены",
  ended: "Завершено",
  contact_button: "Связаться с нами",
  all_day: "Весь день",
  sunset: "На закате",
  leave_review: "Оставить отзыв",
  cancellation_policy_title: "Политика отмены",
  cancellation_policy_desc: "Здесь указаны условия в случае отмены бронирования или плохой погоды.",
  in_case_of_cancellation: "В случае отмены",
  cancel_15: "<strong>До 15 дней до даты:</strong> полный возврат депозита.",
  cancel_7: "<strong>До 7 дней до даты:</strong> возврат 50% депозита.",
  cancel_0: "<strong>В последние 7 дней:</strong> депозит не возвращается.",
  change_date: "Мы всегда готовы перенести дату при наличии свободных мест.",
  in_case_of_bad_weather: "В случае плохой погоды",
  bad_weather_desc: "Если высота волн составляет <strong>1,5 метра или выше</strong>, выход в море невозможен. В этом случае:",
  try_new_date: "Мы постараемся вместе подобрать новую доступную дату.",
  refund: "Если это невозможно, вам вернут всю сумму."
},
zh: {
  reviews_desc: "你搭乘过 Leggero 吗？点击下方链接即可留下评价！谢谢！",
  review_florence_name: "Florence Kollie",
  review_florence_text: "Riccardo 是一位经验丰富的水上向导，低调不打扰，却温暖亲切，如同久别重逢的老朋友。他会让你在一天之内真正感受当地人的意式生活。",
  review_simone_name: "Simone",
  review_simone_text: "Riccardo 的专业与细致让我们的旅程既安全又真实、充满魅力。强烈推荐给想在海上度过难忘一天的人！",
  review_giulia_name: "Giulia",
  review_giulia_text: "一次会留在心里的体验！Riccardo 专业而体贴，让一切都变得简单愉快。迷人的风景、真实的瞬间与独特的氛围让一天转瞬即逝。想要难忘冒险的人别错过！",
  all_inclusive: "全包服务",
  all_inclusive_desc: "船上备有一切所需。轻松出行：无需为打包烦恼，我们都准备好了！",
  photo_souvenir: "纪念照片",
  amenities: "船上设施",
  towels_snacks: "毛巾与新鲜小食",
  snorkeling_gear: "浮潜装备",
  full_face_masks: "全罩式面罩（L）",
  gourmet_desc: "魔幻的夜间巡游，配以精致晚餐、美酒与最美的日落。",
  contact_us: "联系我们！",
  footer_copyright: "© 2025 Leggero Tours",
  footer_credit: "由 Riccardo 用心打造，由 <a href=\"https://www.linkedin.com/in/francescolimosani/\" style=\"font-weight: 600;\">Francesco Limosani</a> 开发",
  stella_maris_desc: "自 15 世纪延续的传统，为渔民祈福；海上巡游，成千上万的灯火点亮夜空。",
  rainbow_tour_desc: "探索野性之地与秘境海湾。从蓬塔基亚帕到波托菲诺，途经帕拉吉与圣弗鲁托索。",
  gourmet_sunset_desc: "在日落时分于博卡达塞抛锚，享用丰盛的利古里亚开胃酒。美食、星空与“跳舞”的海豚！",
  choose_option: "选择一个选项以查看可用性",
  experience: "体验",
  rainbow_tour: "Rainbow Tour",
  people: "人数",
  people_count: "6",
  halfday_morning: "半天（上午）",
  halfday_morning_time: "7:00 - 14:00",
  halfday_afternoon: "半天（下午）",
  halfday_afternoon_time: "14:30 - 18:00",
  fullday: "全天",
  fullday_time: "7:00 - 23:00",
  fullday_desc: "享受整日放松，最后以震撼日落与丰盛意式开胃餐收尾。",
  discount: "立减 40%",
  continue: "继续",
  tour_amazing: "你的行程看起来很棒！",
  date: "日期",
  slot: "时间段",
  group_type: "团队类型",
  combo: "组合",
  final_price: "最终价格",
  your_data: "你的信息",
  name: "名字 <span class='required-star'>*</span>",
  surname: "姓氏 <span class='required-star'>*</span>",
  email: "邮箱 <span class='required-star'>*</span>",
  confirm_email: "确认邮箱 <span class='required-star'>*</span>",
  phone: "电话 <span class='required-star'>*</span>",
  phone_placeholder: "电话号码",
  notes: "备注",
  notes_placeholder: "任何备注…",
  back: "返回",
  book: "预订你的体验",
  live_gulf: "畅游利古里亚海湾！",
  enjoy_peace: "享受私人行程的宁静，或与世界各地的朋友共享体验：旅程自热那亚老港启航，记忆将随你同行。",
  the_experiences: "体验项目",
  customize_experience: "按需定制你的体验！",
  main: "主打",
  special: "特别",
  price_1300: "每团 1300 €",
  price_350: "每团 350 €",
  fuel_included: "含燃油",
  no_surprise: "无额外费用",
  photo: "纪念照片",
  cheese: "茄子！",
  water_sports: "水上运动",
  lets_go: "出发！",
  pet_friendly: "可携带宠物",
  bring_them: "把它们带上！",
  accessible: "无障碍",
  no_one_left: "无人被落下",
  equipment: "装备",
  all_essentials: "所有必需 + 额外！",
  snacks: "小吃与饮品",
  we_like_full: "我们喜欢肚子饱饱的",
  flexible: "灵活",
  change_plans: "轻松更改计划",
  music: "音乐",
  sure: "当然",
  snorkeling: "浮潜装备",
  full_face: "全罩式面罩（L）",
  safety: "安全",
  first_of_all: "首先",
  cancellation_policy_link: "取消政策",
  ended: "已结束",
  contact_button: "联系我们",
  all_day: "整天",
  sunset: "日落时分",
  leave_review: "留下评价",
  cancellation_policy_title: "取消政策",
  cancellation_policy_desc: "此处列出在取消预订或遇到恶劣天气时的相关条款。",
  in_case_of_cancellation: "如需取消",
  cancel_15: "<strong>提前 15 天：</strong>定金全额退还。",
  cancel_7: "<strong>提前 7 天：</strong>退还定金的 50%。",
  cancel_0: "<strong>最后 7 天：</strong>定金不予退还。",
  change_date: "如有空档，我们随时可以改期。",
  in_case_of_bad_weather: "如遇恶劣天气",
  bad_weather_desc: "如果海况出现 <strong>1.5 米或更高</strong> 的浪高，将无法出海。在这种情况下：",
  try_new_date: "我们会一起尝试寻找新的可用日期。",
  refund: "如果无法安排，将全额退款。"
},
};
const FLAGS = {
  it: '/assets/icons/flags/it.svg',
  en: '/assets/icons/flags/gb.svg',
  de: '/assets/icons/flags/de.svg',
  fr: '/assets/icons/flags/fr.svg',
  es: '/assets/icons/flags/es.svg',
  pl: '/assets/icons/flags/pl.svg',
  ru: '/assets/icons/flags/ru.svg',
  zh: '/assets/icons/flags/zh.svg'
};

function getLangFromUrl() {
  const params = new URLSearchParams(window.location.search);
  return params.get('lang') || 'it';
}

function setLangInUrl(lang) {
  const url = new URL(window.location.href);
  url.searchParams.set('lang', lang);
  window.location.href = url.toString();
}

function updateTexts(lang) {
  const dict = TRANSLATIONS[lang] || TRANSLATIONS['it'];

  // Testi classici con data-i18n
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (dict[key]) el.innerHTML = dict[key];
  });

  // Placeholder
  document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
    const key = el.getAttribute('data-i18n-placeholder');
    if (dict[key]) el.setAttribute('placeholder', dict[key]);
  });

  // Bandiera lingua
  if (document.getElementById('lang-flag')) {
    document.getElementById('lang-flag').src = FLAGS[lang] || FLAGS['it'];
  }

  // 🔥 Storybar tradotte (es. Rainbow Tour)
  // Usa data-i18n-story="story_rainbow" nell'HTML della storybar
  document.querySelectorAll('[data-i18n-story]').forEach(el => {
    const key = el.getAttribute('data-i18n-story');
    const steps = dict[key];
    if (steps && Array.isArray(steps)) {
      // Aggiorna l’attributo data-steps con i titoli nella lingua corrente
      el.dataset.steps = steps.join('|');

      // Se l’istanza StoriesProgress è già presente, ricarica i titoli e resetta
      if (el._stories) {
        el._stories.opts.steps = steps.map(title => ({ title }));
        el._stories.goTo(0); // torna alla prima “stanghetta”
      }
    }
  });
}

document.addEventListener('DOMContentLoaded', function() {
  const lang = getLangFromUrl();
  updateTexts(lang);

  // Dropdown lingue
  const toggle = document.getElementById('lang-toggle');
  const menu = document.getElementById('lang-menu');
  if (toggle && menu) {
    toggle.addEventListener('click', (e) => {
      e.stopPropagation();
      menu.style.display = menu.style.display === 'block' ? 'none' : 'block';
    });
    document.addEventListener('click', () => {
      menu.style.display = 'none';
    });
    menu.querySelectorAll('li[data-lang]').forEach(li => {
      li.addEventListener('click', (e) => {
        e.preventDefault();
        setLangInUrl(li.getAttribute('data-lang'));
      });
    });
  }
});


TRANSLATIONS.it.story_rainbow = [
  "Partenza",
  "Traversata",
  "Inchino a Camogli",
  "Colazione sull’altalena",
  "Tuffo a Punta Chiappa",
  "Snorkeling a San Fruttuoso",
  "Shopping a Portofino",
  "Avvistamento delfini",
  "Aperitivo a Boccadasse"
];

TRANSLATIONS.en.story_rainbow = [
  "Departure",
  "Crossing",
  "Salute to Camogli",
  "Breakfast by the swing",
  "Dive at Punta Chiappa",
  "Snorkeling in San Fruttuoso",
  "Shopping in Portofino",
  "Dolphin watching",
  "Aperitif in Boccadasse"
];

TRANSLATIONS.de.story_rainbow = [
  "Abfahrt",
  "Überfahrt",
  "Gruß an Camogli",
  "Frühstück bei der Schaukel",
  "Sprung bei Punta Chiappa",
  "Schnorcheln in San Fruttuoso",
  "Shopping in Portofino",
  "Delfinbeobachtung",
  "Aperitif in Boccadasse"
];

TRANSLATIONS.fr.story_rainbow = [
  "Départ",
  "Traversée",
  "Salut à Camogli",
  "Petit-déjeuner à la balançoire",
  "Plongée à Punta Chiappa",
  "Snorkeling à San Fruttuoso",
  "Shopping à Portofino",
  "Observation des dauphins",
  "Apéritif à Boccadasse"
];

TRANSLATIONS.es.story_rainbow = [
  "Salida",
  "Travesía",
  "Saludo a Camogli",
  "Desayuno en el columpio",
  "Chapuzón en Punta Chiappa",
  "Snorkel en San Fruttuoso",
  "Compras en Portofino",
  "Avistamiento de delfines",
  "Aperitivo en Boccadasse"
];

TRANSLATIONS.pl.story_rainbow = [
  "Wypłynięcie",
  "Przeprawa",
  "Pozdrowienie Camogli",
  "Śniadanie przy huśtawce",
  "Skok do wody w Punta Chiappa",
  "Snorkeling w San Fruttuoso",
  "Zakupy w Portofino",
  "Obserwacja delfinów",
  "Aperitif w Boccadasse"
];

TRANSLATIONS.ru.story_rainbow = [
  "Отправление",
  "Переход",
  "Приветствие Камольи",
  "Завтрак у качели",
  "Прыжок у Пунта Кьяппа",
  "Снорклинг в Сан-Фруттуозо",
  "Шопинг в Портофино",
  "Наблюдение за дельфинами",
  "Аперитив в Боккадассе"
];

TRANSLATIONS.zh.story_rainbow = [
  "出发",
  "航行",
  "向卡莫利致意",
  "秋千上的早餐",
  "在蓬塔基亚帕跳水",
  "在圣弗鲁托索浮潜",
  "在波托菲诺购物",
  "观赏海豚",
  "在博卡达塞享用开胃酒"
];
