// lang.js - gestione multilingua via ?lang=xx

const TRANSLATIONS = {
  it: {
    // Booking
    choose_option: "Scegli un opzione per scoprire la disponibilità",
    experience: "Esperienza",
    rainbow_tour: "Rainbow Tour",
    people: "Persone",
    people_count: "6",
    halfday_morning: "Mezza giornata (Mattina)",
    halfday_morning_time: "7:00 - 14:00",
    halfday_afternoon: "Mezza giornata (Pomeriggio)",
    halfday_afternoon_time: "14:30 - 18:00",
    fullday: "Giornata intera",
    fullday_time: "7:00 - 23:00",
    fullday_desc: "Goditi una giornata di relax che termina con un tramonto mozzafiato e un ricco aperitivo italiano.",
    discount: "40% SCONTO",
    continue: "Continua",
    tour_amazing: "Il tuo tour sembra fantastico!",
    date: "Data",
    slot: "Fascia oraria",
    group_type: "Tipo gruppo",
    combo: "Combinazione",
    final_price: "Prezzo finale",
    your_data: "I tuoi dati",
    name: "Nome <span class='required-star'>*</span>",
    surname: "Cognome <span class='required-star'>*</span>",
    email: "Email <span class='required-star'>*</span>",
    confirm_email: "Conferma Email <span class='required-star'>*</span>",
    phone: "Telefono <span class='required-star'>*</span>",
    phone_placeholder: "Numero di telefono",
    notes: "Note",
    notes_placeholder: "Eventuali note...",
    back: "Indietro",
    book: "Prenota la tua esperienza",
    // Index
    live_gulf: "Vivi il golfo Ligure!",
    enjoy_peace: "Goditi la pace di un tour privato o condividi l’esperienza con persone da tutto il mondo: il viaggio parte dal Porto Antico di Genova, ma il ricordo resta con te.",
    the_experiences: "Le esperienze",
    customize_experience: "Personalizza la tua esperienza secondo le tue esigenze!<br>Oppure contattaci per un tour esclusivo!",
    main: "Principali",
    special: "Speciali",
    price_1300: "1300 € a gruppo",
    price_350: "350 € a gruppo",
    fuel_included: "Carburante Incluso",
    no_surprise: "Nessuna sorpresa extra",
    photo: "Foto Ricordo",
    cheese: "Cheese!",
    water_sports: "Sport Acquatici",
    lets_go: "Andiamo!",
    pet_friendly: "Pet Friendly",
    bring_them: "Portali con te!",
    accessible: "Accessibile Disabili",
    no_one_left: "Nessuno resta indietro",
    equipment: "Dotazioni",
    all_essentials: "Tutto l’essenziale + extra!",
    snacks: "Snack & Bevande",
    we_like_full: "Ci piace la pancia piena",
    flexible: "Flessibile",
    change_plans: "Cambia piani facilmente",
    music: "Musica",
    sure: "Certo",
    snorkeling: "Attrezzatura Snorkeling",
    full_face: "Maschere full face (L)",
    safety: "Sicurezza",
    first_of_all: "Prima di tutto",
    cancellation_policy_link: "Politica di cancellazione",
    // Cancellation
    cancellation_policy_title: "Politica di Cancellazione",
    cancellation_policy_desc: "Qui trovi le condizioni in caso di rinuncia alla prenotazione o maltempo.",
    in_case_of_cancellation: "In caso di cancellazione",
    cancel_15: "<strong>Fino a 15 giorni prima:</strong> rimborso completo del deposito.",
    cancel_7: "<strong>Fino a 7 giorni prima:</strong> rimborso del 50% del deposito.",
    cancel_0: "<strong>Negli ultimi 7 giorni:</strong> nessun rimborso del deposito.",
    change_date: "Siamo sempre disponibili a spostare la data, compatibilmente con la disponibilità.",
    in_case_of_bad_weather: "In caso di maltempo",
    bad_weather_desc: "Se il mare presenta onde di <strong>1.5 metri o più</strong>, non sarà possibile uscire in barca. In questo caso:",
    try_new_date: "Proveremo a trovare insieme una nuova data disponibile.",
    refund: "Se non fosse possibile, ti verrà restituito l’intero importo."
  },
  en: {
    // Booking
    choose_option: "Choose an option to check availability",
    experience: "Experience",
    rainbow_tour: "Rainbow Tour",
    people: "People",
    people_count: "6",
    halfday_morning: "Half Day (Morning)",
    halfday_morning_time: "7:00AM - 2:00 PM",
    halfday_afternoon: "Half Day (Afternoon)",
    halfday_afternoon_time: "2:30PM - 6:00 PM",
    fullday: "Full Day",
    fullday_time: "7:00AM - 11:00 PM",
    fullday_desc: "Enjoy a full day of relaxation, ending with a breathtaking sunset and a rich Italian aperitivo.",
    discount: "40% OFF",
    continue: "Continue",
    tour_amazing: "Your Tour looks amazing!",
    date: "Date",
    slot: "Slot",
    group_type: "Group Type",
    combo: "Combo",
    final_price: "Final Price",
    your_data: "Your Data",
    name: "Name <span class='required-star'>*</span>",
    surname: "Surname <span class='required-star'>*</span>",
    email: "Email <span class='required-star'>*</span>",
    confirm_email: "Confirm Email <span class='required-star'>*</span>",
    phone: "Phone <span class='required-star'>*</span>",
    phone_placeholder: "Phone number",
    notes: "Notes",
    notes_placeholder: "Any notes...",
    back: "Back",
    book: "Book your experience",
    // Index
    live_gulf: "Live the Ligurian Gulf!",
    enjoy_peace: "Enjoy the peace of a private tour or share the experience with people from all over the world: the journey starts from Genoa's Old Port, but the memory stays with you.",
    the_experiences: "The experiences",
    customize_experience: "Customize your experience according to your needs!<br>Or contact us for an exclusive tour!",
    main: "Main",
    special: "Special",
    price_1300: "1300 € per group",
    price_350: "350 € per group",
    fuel_included: "Fuel Included",
    no_surprise: "No extra surprises",
    photo: "Souvenir Photo",
    cheese: "Cheese!",
    water_sports: "Water Sports",
    lets_go: "Let's go!",
    pet_friendly: "Pet Friendly",
    bring_them: "Bring them with you!",
    accessible: "Accessible for Disabled",
    no_one_left: "No one left behind",
    equipment: "Equipment",
    all_essentials: "All essentials + extras!",
    snacks: "Snacks & Drinks",
    we_like_full: "We like full bellies",
    flexible: "Flexible",
    change_plans: "Change plans easily",
    music: "Music",
    sure: "Sure",
    snorkeling: "Snorkeling Equipment",
    full_face: "Full face masks (L)",
    safety: "Safety",
    first_of_all: "First of all",
    cancellation_policy_link: "Cancellation Policy",
    // Cancellation
    cancellation_policy_title: "Cancellation Policy",
    cancellation_policy_desc: "Here you find the conditions in case of booking cancellation or bad weather.",
    in_case_of_cancellation: "In case of cancellation",
    cancel_15: "<strong>Up to 15 days before:</strong> full refund of the deposit.",
    cancel_7: "<strong>Up to 7 days before:</strong> 50% refund of the deposit.",
    cancel_0: "<strong>In the last 7 days:</strong> no refund of the deposit.",
    change_date: "We are always available to reschedule, subject to availability.",
    in_case_of_bad_weather: "In case of bad weather",
    bad_weather_desc: "If the sea has waves of <strong>1.5 meters or more</strong>, it will not be possible to go out by boat. In this case:",
    try_new_date: "We will try to find a new available date together.",
    refund: "If not possible, you will be refunded the full amount."
  },
  de: {
    // Booking
    choose_option: "Wähle eine Option, um die Verfügbarkeit zu prüfen",
    experience: "Erlebnis",
    rainbow_tour: "Rainbow Tour",
    people: "Personen",
    people_count: "6",
    halfday_morning: "Halber Tag (Morgen)",
    halfday_morning_time: "7:00 - 14:00",
    halfday_afternoon: "Halber Tag (Nachmittag)",
    halfday_afternoon_time: "14:30 - 18:00",
    fullday: "Ganzer Tag",
    fullday_time: "7:00 - 23:00",
    fullday_desc: "Genießen Sie einen entspannten Tag mit atemberaubendem Sonnenuntergang und italienischem Aperitif.",
    discount: "40% RABATT",
    continue: "Weiter",
    tour_amazing: "Ihre Tour sieht fantastisch aus!",
    date: "Datum",
    slot: "Zeitfenster",
    group_type: "Gruppentyp",
    combo: "Kombination",
    final_price: "Endpreis",
    your_data: "Ihre Daten",
    name: "Name <span class='required-star'>*</span>",
    surname: "Nachname <span class='required-star'>*</span>",
    email: "E-Mail <span class='required-star'>*</span>",
    confirm_email: "E-Mail bestätigen <span class='required-star'>*</span>",
    phone: "Telefon <span class='required-star'>*</span>",
    phone_placeholder: "Telefonnummer",
    notes: "Notizen",
    notes_placeholder: "Weitere Hinweise...",
    back: "Zurück",
    book: "Erlebnis buchen",
    // Index
    live_gulf: "Erleben Sie den Golf von Ligurien!",
    enjoy_peace: "Genießen Sie die Ruhe einer privaten Tour oder teilen Sie das Erlebnis mit Menschen aus aller Welt: Die Reise beginnt im Alten Hafen von Genua, aber die Erinnerung bleibt.",
    the_experiences: "Die Erlebnisse",
    customize_experience: "Passen Sie Ihr Erlebnis an Ihre Wünsche an!<br>Oder kontaktieren Sie uns für eine exklusive Tour!",
    main: "Haupttouren",
    special: "Spezialtouren",
    price_1300: "1300 € pro Gruppe",
    price_350: "350 € pro Gruppe",
    fuel_included: "Kraftstoff inklusive",
    no_surprise: "Keine versteckten Kosten",
    photo: "Erinnerungsfoto",
    cheese: "Cheese!",
    water_sports: "Wassersport",
    lets_go: "Los geht's!",
    pet_friendly: "Haustierfreundlich",
    bring_them: "Bringen Sie sie mit!",
    accessible: "Barrierefrei",
    no_one_left: "Niemand bleibt zurück",
    equipment: "Ausstattung",
    all_essentials: "Alles Notwendige + Extras!",
    snacks: "Snacks & Getränke",
    we_like_full: "Wir mögen volle Bäuche",
    flexible: "Flexibel",
    change_plans: "Pläne einfach ändern",
    music: "Musik",
    sure: "Natürlich",
    snorkeling: "Schnorchelausrüstung",
    full_face: "Vollgesichtsmasken (L)",
    safety: "Sicherheit",
    first_of_all: "An erster Stelle",
    cancellation_policy_link: "Stornierungsbedingungen",
    // Cancellation
    cancellation_policy_title: "Stornierungsbedingungen",
    cancellation_policy_desc: "Hier finden Sie die Bedingungen bei Stornierung oder schlechtem Wetter.",
    in_case_of_cancellation: "Im Falle einer Stornierung",
    cancel_15: "<strong>Bis 15 Tage vorher:</strong> volle Rückerstattung der Anzahlung.",
    cancel_7: "<strong>Bis 7 Tage vorher:</strong> 50% Rückerstattung der Anzahlung.",
    cancel_0: "<strong>In den letzten 7 Tagen:</strong> keine Rückerstattung der Anzahlung.",
    change_date: "Wir sind immer bereit, das Datum nach Verfügbarkeit zu ändern.",
    in_case_of_bad_weather: "Bei schlechtem Wetter",
    bad_weather_desc: "Wenn das Meer Wellen von <strong>1,5 Metern oder mehr</strong> hat, ist eine Ausfahrt nicht möglich. In diesem Fall:",
    try_new_date: "Wir versuchen gemeinsam ein neues Datum zu finden.",
    refund: "Falls nicht möglich, erhalten Sie den vollen Betrag zurück."
  },
  fr: {
    choose_option: "Choisissez une option pour vérifier la disponibilité",
    experience: "Expérience",
    rainbow_tour: "Rainbow Tour",
    people: "Personnes",
    people_count: "6",
    halfday_morning: "Demi-journée (matin)",
    halfday_morning_time: "7h00 - 14h00",
    halfday_afternoon: "Demi-journée (après-midi)",
    halfday_afternoon_time: "14h30 - 18h00",
    fullday: "Journée complète",
    fullday_time: "7h00 - 23h00",
    fullday_desc: "Profitez d'une journée de détente, d'un coucher de soleil et d'un apéritif italien.",
    discount: "40% RÉDUCTION",
    continue: "Continuer",
    tour_amazing: "Votre tour est incroyable !",
    date: "Date",
    slot: "Créneau",
    group_type: "Type de groupe",
    combo: "Combo",
    final_price: "Prix final",
    your_data: "Vos informations",
    name: "Prénom <span class='required-star'>*</span>",
    surname: "Nom <span class='required-star'>*</span>",
    email: "E-mail <span class='required-star'>*</span>",
    confirm_email: "Confirmer l'e-mail <span class='required-star'>*</span>",
    phone: "Téléphone <span class='required-star'>*</span>",
    phone_placeholder: "Numéro de téléphone",
    notes: "Notes",
    notes_placeholder: "Notes éventuelles...",
    back: "Retour",
    book: "Réserver votre expérience",
    live_gulf: "Vivez le golfe ligure !",
    enjoy_peace: "Profitez de la tranquillité d'une visite privée ou partagez l'expérience avec des personnes du monde entier : le voyage commence au Vieux-Port de Gênes, mais le souvenir reste.",
    the_experiences: "Les expériences",
    customize_experience: "Personnalisez votre expérience selon vos besoins !<br>Ou contactez-nous pour une visite exclusive !",
    main: "Principales",
    special: "Spéciales",
    price_1300: "1300 € par groupe",
    price_350: "350 € par groupe",
    fuel_included: "Carburant inclus",
    no_surprise: "Aucune surprise",
    photo: "Photo souvenir",
    cheese: "Cheese!",
    water_sports: "Sports nautiques",
    lets_go: "Allons-y !",
    pet_friendly: "Animaux acceptés",
    bring_them: "Emmenez-les avec vous !",
    accessible: "Accessible PMR",
    no_one_left: "Personne n'est laissé de côté",
    equipment: "Équipement",
    all_essentials: "Tout le nécessaire + extra !",
    snacks: "Snacks & Boissons",
    we_like_full: "On aime avoir le ventre plein",
    flexible: "Flexible",
    change_plans: "Changez de plans facilement",
    music: "Musique",
    sure: "Bien sûr",
    snorkeling: "Équipement de snorkeling",
    full_face: "Masques intégraux (L)",
    safety: "Sécurité",
    first_of_all: "Avant tout",
    cancellation_policy_link: "Politique d'annulation",
    cancellation_policy_title: "Politique d'annulation",
    cancellation_policy_desc: "Vous trouverez ici les conditions en cas d'annulation ou de mauvais temps.",
    in_case_of_cancellation: "En cas d'annulation",
    cancel_15: "<strong>Jusqu'à 15 jours avant :</strong> remboursement total de l'acompte.",
    cancel_7: "<strong>Jusqu'à 7 jours avant :</strong> remboursement de 50% de l'acompte.",
    cancel_0: "<strong>Dans les 7 derniers jours :</strong> aucun remboursement de l'acompte.",
    change_date: "Nous sommes toujours disponibles pour changer la date, selon disponibilité.",
    in_case_of_bad_weather: "En cas de mauvais temps",
    bad_weather_desc: "Si la mer a des vagues de <strong>1,5 mètre ou plus</strong>, il ne sera pas possible de sortir en bateau. Dans ce cas :",
    try_new_date: "Nous essaierons de trouver une nouvelle date ensemble.",
    refund: "Si ce n'est pas possible, vous serez remboursé intégralement."
  },
  es: {
    choose_option: "Elige una opción para comprobar la disponibilidad",
    experience: "Experiencia",
    rainbow_tour: "Rainbow Tour",
    people: "Personas",
    people_count: "6",
    halfday_morning: "Medio día (mañana)",
    halfday_morning_time: "7:00 - 14:00",
    halfday_afternoon: "Medio día (tarde)",
    halfday_afternoon_time: "14:30 - 18:00",
    fullday: "Día completo",
    fullday_time: "7:00 - 23:00",
    fullday_desc: "Disfruta de un día de relax, con una puesta de sol y un aperitivo italiano.",
    discount: "40% DESCUENTO",
    continue: "Continuar",
    tour_amazing: "¡Tu tour es increíble!",
    date: "Fecha",
    slot: "Horario",
    group_type: "Tipo de grupo",
    combo: "Combo",
    final_price: "Precio final",
    your_data: "Tus datos",
    name: "Nombre <span class='required-star'>*</span>",
    surname: "Apellido <span class='required-star'>*</span>",
    email: "Correo electrónico <span class='required-star'>*</span>",
    confirm_email: "Confirmar correo <span class='required-star'>*</span>",
    phone: "Teléfono <span class='required-star'>*</span>",
    phone_placeholder: "Número de teléfono",
    notes: "Notas",
    notes_placeholder: "Notas adicionales...",
    back: "Atrás",
    book: "Reserva tu experiencia",
    live_gulf: "¡Vive el golfo de Liguria!",
    enjoy_peace: "Disfruta de la tranquilidad de un tour privado o comparte la experiencia con personas de todo el mundo: el viaje comienza en el Puerto Antiguo de Génova, pero el recuerdo permanece.",
    the_experiences: "Las experiencias",
    customize_experience: "¡Personaliza tu experiencia según tus necesidades!<br>O contáctanos para un tour exclusivo!",
    main: "Principales",
    special: "Especiales",
    price_1300: "1300 € por grupo",
    price_350: "350 € por grupo",
    fuel_included: "Combustible incluido",
    no_surprise: "Sin sorpresas extra",
    photo: "Foto recuerdo",
    cheese: "¡Cheese!",
    water_sports: "Deportes acuáticos",
    lets_go: "¡Vamos!",
    pet_friendly: "Pet Friendly",
    bring_them: "¡Tráelos contigo!",
    accessible: "Accesible",
    no_one_left: "Nadie se queda atrás",
    equipment: "Equipamiento",
    all_essentials: "Todo lo esencial + extras!",
    snacks: "Snacks y bebidas",
    we_like_full: "Nos gusta la barriga llena",
    flexible: "Flexible",
    change_plans: "Cambia de planes fácilmente",
    music: "Música",
    sure: "Por supuesto",
    snorkeling: "Equipo de snorkel",
    full_face: "Máscaras integrales (L)",
    safety: "Seguridad",
    first_of_all: "Ante todo",
    cancellation_policy_link: "Política de cancelación",
    cancellation_policy_title: "Política de cancelación",
    cancellation_policy_desc: "Aquí encuentras las condiciones en caso de cancelación o mal tiempo.",
    in_case_of_cancellation: "En caso de cancelación",
    cancel_15: "<strong>Hasta 15 días antes:</strong> reembolso total del depósito.",
    cancel_7: "<strong>Hasta 7 días antes:</strong> reembolso del 50% del depósito.",
    cancel_0: "<strong>En los últimos 7 días:</strong> sin reembolso del depósito.",
    change_date: "Siempre estamos disponibles para cambiar la fecha, según disponibilidad.",
    in_case_of_bad_weather: "En caso de mal tiempo",
    bad_weather_desc: "Si el mar tiene olas de <strong>1,5 metros o más</strong>, no será posible salir en barco. En este caso:",
    try_new_date: "Intentaremos encontrar juntos una nueva fecha disponible.",
    refund: "Si no es posible, se te devolverá el importe total."
  },
  pl: {
    choose_option: "Wybierz opcję, aby sprawdzić dostępność",
    experience: "Doświadczenie",
    rainbow_tour: "Rainbow Tour",
    people: "Osoby",
    people_count: "6",
    halfday_morning: "Pół dnia (rano)",
    halfday_morning_time: "7:00 - 14:00",
    halfday_afternoon: "Pół dnia (popołudnie)",
    halfday_afternoon_time: "14:30 - 18:00",
    fullday: "Cały dzień",
    fullday_time: "7:00 - 23:00",
    fullday_desc: "Ciesz się dniem relaksu, zachodem słońca i włoskim aperitifem.",
    discount: "40% ZNIŻKI",
    continue: "Dalej",
    tour_amazing: "Twoja wycieczka wygląda niesamowicie!",
    date: "Data",
    slot: "Godzina",
    group_type: "Typ grupy",
    combo: "Kombinacja",
    final_price: "Cena końcowa",
    your_data: "Twoje dane",
    name: "Imię <span class='required-star'>*</span>",
    surname: "Nazwisko <span class='required-star'>*</span>",
    email: "E-mail <span class='required-star'>*</span>",
    confirm_email: "Potwierdź e-mail <span class='required-star'>*</span>",
    phone: "Telefon <span class='required-star'>*</span>",
    phone_placeholder: "Numer telefonu",
    notes: "Notatki",
    notes_placeholder: "Dodatkowe uwagi...",
    back: "Wstecz",
    book: "Zarezerwuj doświadczenie",
    live_gulf: "Przeżyj Zatokę Liguryjską!",
    enjoy_peace: "Ciesz się spokojem prywatnej wycieczki lub podziel się doświadczeniem z ludźmi z całego świata: podróż zaczyna się w Starym Porcie w Genui, ale wspomnienie zostaje z Tobą.",
    the_experiences: "Doświadczenia",
    customize_experience: "Dostosuj swoje doświadczenie do swoich potrzeb!<br>Lub skontaktuj się z nami po ekskluzywną wycieczkę!",
    main: "Główne",
    special: "Specjalne",
    price_1300: "1300 € za grupę",
    price_350: "350 € za grupę",
    fuel_included: "Paliwo w cenie",
    no_surprise: "Brak ukrytych kosztów",
    photo: "Zdjęcie pamiątkowe",
    cheese: "Cheese!",
    water_sports: "Sporty wodne",
    lets_go: "Jedziemy!",
    pet_friendly: "Przyjazny zwierzętom",
    bring_them: "Zabierz je ze sobą!",
    accessible: "Dostępny dla niepełnosprawnych",
    no_one_left: "Nikt nie zostaje w tyle",
    equipment: "Wyposażenie",
    all_essentials: "Wszystko co potrzebne + dodatki!",
    snacks: "Przekąski i napoje",
    we_like_full: "Lubimy pełne brzuchy",
    flexible: "Elastyczny",
    change_plans: "Łatwa zmiana planów",
    music: "Muzyka",
    sure: "Oczywiście",
    snorkeling: "Sprzęt do nurkowania",
    full_face: "Maski pełnotwarzowe (L)",
    safety: "Bezpieczeństwo",
    first_of_all: "Przede wszystkim",
    cancellation_policy_link: "Polityka anulowania",
    cancellation_policy_title: "Polityka anulowania",
    cancellation_policy_desc: "Tutaj znajdziesz warunki w przypadku anulowania lub złej pogody.",
    in_case_of_cancellation: "W przypadku anulowania",
    cancel_15: "<strong>Do 15 dni przed:</strong> pełny zwrot zaliczki.",
    cancel_7: "<strong>Do 7 dni przed:</strong> zwrot 50% zaliczki.",
    cancel_0: "<strong>W ostatnich 7 dniach:</strong> brak zwrotu zaliczki.",
    change_date: "Zawsze możemy zmienić termin, jeśli są wolne miejsca.",
    in_case_of_bad_weather: "W przypadku złej pogody",
    bad_weather_desc: "Jeśli na morzu są fale o wysokości <strong>1,5 metra lub więcej</strong>, nie będzie można wypłynąć. W takim przypadku:",
    try_new_date: "Postaramy się znaleźć nowy termin.",
    refund: "Jeśli to niemożliwe, otrzymasz pełny zwrot."
  },
  ru: {
    choose_option: "Выберите вариант, чтобы проверить доступность",
    experience: "Экскурсия",
    rainbow_tour: "Rainbow Tour",
    people: "Человек",
    people_count: "6",
    halfday_morning: "Полдня (утро)",
    halfday_morning_time: "7:00 - 14:00",
    halfday_afternoon: "Полдня (день)",
    halfday_afternoon_time: "14:30 - 18:00",
    fullday: "Весь день",
    fullday_time: "7:00 - 23:00",
    fullday_desc: "Наслаждайтесь днем отдыха, закатом и итальянским аперитивом.",
    discount: "СКИДКА 40%",
    continue: "Продолжить",
    tour_amazing: "Ваша экскурсия выглядит потрясающе!",
    date: "Дата",
    slot: "Время",
    group_type: "Тип группы",
    combo: "Комбо",
    final_price: "Итоговая цена",
    your_data: "Ваши данные",
    name: "Имя <span class='required-star'>*</span>",
    surname: "Фамилия <span class='required-star'>*</span>",
    email: "E-mail <span class='required-star'>*</span>",
    confirm_email: "Подтвердите e-mail <span class='required-star'>*</span>",
    phone: "Телефон <span class='required-star'>*</span>",
    phone_placeholder: "Номер телефона",
    notes: "Заметки",
    notes_placeholder: "Дополнительные заметки...",
    back: "Назад",
    book: "Забронировать экскурсию",
    live_gulf: "Откройте для себя Лигурийский залив!",
    enjoy_peace: "Наслаждайтесь спокойствием частной экскурсии или разделите опыт с людьми со всего мира: путешествие начинается в Старом порту Генуи, но воспоминания останутся с вами.",
    the_experiences: "Экскурсии",
    customize_experience: "Настройте свой опыт под себя!<br>Или свяжитесь с нами для эксклюзивного тура!",
    main: "Основные",
    special: "Специальные",
    price_1300: "1300 € за группу",
    price_350: "350 € за группу",
    fuel_included: "Топливо включено",
    no_surprise: "Без скрытых платежей",
    photo: "Фото на память",
    cheese: "Cheese!",
    water_sports: "Водные виды спорта",
    lets_go: "Поехали!",
    pet_friendly: "Можно с животными",
    bring_them: "Берите их с собой!",
    accessible: "Доступно для инвалидов",
    no_one_left: "Никто не останется позади",
    equipment: "Оборудование",
    all_essentials: "Все необходимое + дополнительно!",
    snacks: "Закуски и напитки",
    we_like_full: "Любим быть сытыми",
    flexible: "Гибко",
    change_plans: "Легко изменить планы",
    music: "Музыка",
    sure: "Конечно",
    snorkeling: "Снаряжение для сноркелинга",
    full_face: "Маски full face (L)",
    safety: "Безопасность",
    first_of_all: "Прежде всего",
    cancellation_policy_link: "Политика отмены",
    cancellation_policy_title: "Политика отмены",
    cancellation_policy_desc: "Здесь вы найдете условия отмены или плохой погоды.",
    in_case_of_cancellation: "В случае отмены",
    cancel_15: "<strong>До 15 дней:</strong> полный возврат депозита.",
    cancel_7: "<strong>До 7 дней:</strong> возврат 50% депозита.",
    cancel_0: "<strong>За последние 7 дней:</strong> депозит не возвращается.",
    change_date: "Мы всегда готовы перенести дату при наличии мест.",
    in_case_of_bad_weather: "В случае плохой погоды",
    bad_weather_desc: "Если на море волны <strong>1,5 метра и выше</strong>, выход невозможен. В этом случае:",
    try_new_date: "Попробуем найти новую дату.",
    refund: "Если невозможно — вернем всю сумму."
  },
  zh: {
    choose_option: "选择一个选项以查看可用性",
    experience: "体验",
    rainbow_tour: "彩虹之旅",
    people: "人数",
    people_count: "6",
    halfday_morning: "半天（上午）",
    halfday_morning_time: "7:00 - 14:00",
    halfday_afternoon: "半天（下午）",
    halfday_afternoon_time: "14:30 - 18:00",
    fullday: "全天",
    fullday_time: "7:00 - 23:00",
    fullday_desc: "享受一天的放松，日落和意大利开胃酒。",
    discount: "立减40%",
    continue: "继续",
    tour_amazing: "您的行程很棒！",
    date: "日期",
    slot: "时段",
    group_type: "团体类型",
    combo: "组合",
    final_price: "最终价格",
    your_data: "您的信息",
    name: "名字 <span class='required-star'>*</span>",
    surname: "姓氏 <span class='required-star'>*</span>",
    email: "邮箱 <span class='required-star'>*</span>",
    confirm_email: "确认邮箱 <span class='required-star'>*</span>",
    phone: "电话 <span class='required-star'>*</span>",
    phone_placeholder: "电话号码",
    notes: "备注",
    notes_placeholder: "其他备注...",
    back: "返回",
    book: "预订您的体验",
    live_gulf: "体验利古里亚湾！",
    enjoy_peace: "享受私人游的宁静，或与来自世界各地的人们分享体验：旅程从热那亚老港开始，但回忆将伴随您。",
    the_experiences: "体验项目",
    customize_experience: "根据您的需求定制体验！<br>或联系我们获取专属行程！",
    main: "主要",
    special: "特别",
    price_1300: "每组1300欧元",
    price_350: "每组350欧元",
    fuel_included: "包含燃油",
    no_surprise: "无额外费用",
    photo: "纪念照片",
    cheese: "茄子！",
    water_sports: "水上运动",
    lets_go: "出发！",
    pet_friendly: "可携带宠物",
    bring_them: "带上它们！",
    accessible: "无障碍",
    no_one_left: "无人被落下",
    equipment: "装备",
    all_essentials: "所有必需品+额外！",
    snacks: "小吃和饮品",
    we_like_full: "我们喜欢吃饱喝足",
    flexible: "灵活",
    change_plans: "轻松更改计划",
    music: "音乐",
    sure: "当然",
    snorkeling: "浮潜装备",
    full_face: "全罩面罩 (L)",
    safety: "安全",
    first_of_all: "最重要",
    cancellation_policy_link: "取消政策",
    cancellation_policy_title: "取消政策",
    cancellation_policy_desc: "这里有关于取消或恶劣天气的条款。",
    in_case_of_cancellation: "如需取消",
    cancel_15: "<strong>提前15天：</strong>全额退还定金。",
    cancel_7: "<strong>提前7天：</strong>退还50%定金。",
    cancel_0: "<strong>最后7天：</strong>定金不退。",
    change_date: "如有空位，我们可随时更改日期。",
    in_case_of_bad_weather: "遇恶劣天气",
    bad_weather_desc: "如遇<strong>1.5米或更高</strong>的海浪，将无法出海。此时：",
    try_new_date: "我们会一起尝试找新日期。",
    refund: "如无法安排，将全额退款。"
  }
};

const FLAGS = {
  it: '/assets/icons/flags/it.svg',
  en: '/assets/icons/flags/gb.svg',
  de: '/assets/icons/flags/de.svg',
  fr: '/assets/icons/flags/fr.svg',
  es: '/assets/icons/flags/es.svg',
  pl: '/assets/icons/flags/pl.svg',
  ru: '/assets/icons/flags/ru.svg',
  zh: '/assets/icons/flags/zh.svg'
};

function getLangFromUrl() {
  const params = new URLSearchParams(window.location.search);
  return params.get('lang') || 'it';
}

function setLangInUrl(lang) {
  const url = new URL(window.location.href);
  url.searchParams.set('lang', lang);
  window.location.href = url.toString();
}

function updateTexts(lang) {
  const dict = TRANSLATIONS[lang] || TRANSLATIONS['it'];
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (dict[key]) el.innerHTML = dict[key];
  });
  document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
    const key = el.getAttribute('data-i18n-placeholder');
    if (dict[key]) el.setAttribute('placeholder', dict[key]);
  });
  // Aggiorna bandiera
  if(document.getElementById('lang-flag')) {
    document.getElementById('lang-flag').src = FLAGS[lang] || FLAGS['it'];
  }
}

document.addEventListener('DOMContentLoaded', function() {
  const lang = getLangFromUrl();
  updateTexts(lang);
  // Dropdown
  const toggle = document.getElementById('lang-toggle');
  const menu = document.getElementById('lang-menu');
  if(toggle && menu) {
    toggle.addEventListener('click', (e) => {
      e.stopPropagation();
      menu.style.display = menu.style.display === 'block' ? 'none' : 'block';
    });
    document.addEventListener('click', () => {
      menu.style.display = 'none';
    });
    menu.querySelectorAll('li[data-lang]').forEach(li => {
      li.addEventListener('click', (e) => {
        e.preventDefault();
        setLangInUrl(li.getAttribute('data-lang'));
      });
    });
  }
});
