export const additionalBookingUi = {
  pt: {
    select: 'Selecionar', experience: 'Experiência', guests: 'Pessoas', time: 'Hora', date: 'Data', ports: 'Portos',
    chooseExperience: 'Escolha uma experiência', chooseExperienceHint: 'Selecione uma experiência para continuar.', guestQuestion: 'Quantas pessoas?', decreaseGuests: 'Diminuir pessoas', increaseGuests: 'Aumentar pessoas', chooseTime: 'Escolha a hora', chooseDate: 'Escolha a data', portsTitle: 'Portos e transfer', portsHint: 'Escolha os portos de partida e chegada e os transfers privados.', continue: 'Continuar', back: 'Voltar', review: 'Rever resumo', noBoats: 'Nenhum barco disponível com estes filtros', reset: 'Repor filtros', showAll: 'Ver todas as experiências', formName: 'Como se chama?', formPhone: 'Qual é o seu telefone?', formEmail: 'Qual é o seu e-mail?', formNotes: 'Tem algum pedido especial?', optional: 'Opcional', boats: 'Barcos', availabilityAria: 'Disponibilidade da experiência selecionada', customizeExperience: (title) => `Personalize "${title}"`, filtersTitle: 'Pessoas, hora e data', forExperience: (title) => `Para ${title}.`, chooseStart: 'Escolha uma experiência para começar.',
  },
  nl: {
    select: 'Selecteren', experience: 'Ervaring', guests: 'Gasten', time: 'Tijd', date: 'Datum', ports: 'Havens',
    chooseExperience: 'Kies een ervaring', chooseExperienceHint: 'Selecteer een ervaring om door te gaan.', guestQuestion: 'Hoeveel gasten?', decreaseGuests: 'Minder gasten', increaseGuests: 'Meer gasten', chooseTime: 'Kies een tijd', chooseDate: 'Kies een datum', portsTitle: 'Havens en transfer', portsHint: 'Kies de vertrek- en aankomsthaven en eventuele privétransfers.', continue: 'Doorgaan', back: 'Terug', review: 'Overzicht bekijken', noBoats: 'Geen boten beschikbaar voor deze filters', reset: 'Filters wissen', showAll: 'Alle ervaringen tonen', formName: 'Wat is je naam?', formPhone: 'Wat is je telefoonnummer?', formEmail: 'Wat is je e-mailadres?', formNotes: 'Speciale wensen?', optional: 'Optioneel', boats: 'Boten', availabilityAria: 'Beschikbaarheid geselecteerde ervaring', customizeExperience: (title) => `Pas "${title}" aan`, filtersTitle: 'Gasten, tijd en datum', forExperience: (title) => `Voor ${title}.`, chooseStart: 'Kies een ervaring om te beginnen.',
  },
  he: {
    select: 'בחירה', experience: 'חוויה', guests: 'אורחים', time: 'שעה', date: 'תאריך', ports: 'נמלים',
    chooseExperience: 'בחרו חוויה', chooseExperienceHint: 'בחרו חוויה כדי להמשיך.', guestQuestion: 'כמה אורחים?', decreaseGuests: 'הפחתת אורחים', increaseGuests: 'הוספת אורחים', chooseTime: 'בחרו שעה', chooseDate: 'בחרו תאריך', portsTitle: 'נמלים והעברה', portsHint: 'בחרו נמל יציאה, נמל הגעה והעברות פרטיות.', continue: 'המשך', back: 'חזרה', review: 'בדיקת הסיכום', noBoats: 'אין סירות זמינות למסננים אלה', reset: 'איפוס מסננים', showAll: 'הצגת כל החוויות', formName: 'מה שמכם?', formPhone: 'מה מספר הטלפון?', formEmail: 'מה כתובת הדוא״ל?', formNotes: 'בקשות מיוחדות?', optional: 'לא חובה', boats: 'סירות', availabilityAria: 'זמינות החוויה שנבחרה', customizeExperience: (title) => `התאמת "${title}"`, filtersTitle: 'אורחים, שעה ותאריך', forExperience: (title) => `עבור ${title}.`, chooseStart: 'בחרו חוויה כדי להתחיל.',
  },
  cs: {
    select: 'Vybrat', experience: 'Zážitek', guests: 'Hosté', time: 'Čas', date: 'Datum', ports: 'Přístavy',
    chooseExperience: 'Vyberte zážitek', chooseExperienceHint: 'Pro pokračování vyberte zážitek.', guestQuestion: 'Kolik hostů?', decreaseGuests: 'Méně hostů', increaseGuests: 'Více hostů', chooseTime: 'Vyberte čas', chooseDate: 'Vyberte datum', portsTitle: 'Přístavy a transfer', portsHint: 'Vyberte přístav odjezdu a příjezdu a soukromé transfery.', continue: 'Pokračovat', back: 'Zpět', review: 'Zkontrolovat souhrn', noBoats: 'Pro tyto filtry nejsou dostupné lodě', reset: 'Obnovit filtry', showAll: 'Zobrazit všechny zážitky', formName: 'Jak se jmenujete?', formPhone: 'Jaké je vaše telefonní číslo?', formEmail: 'Jaký je váš e-mail?', formNotes: 'Máte zvláštní požadavky?', optional: 'Volitelné', boats: 'Lodě', availabilityAria: 'Dostupnost vybraného zážitku', customizeExperience: (title) => `Upravit "${title}"`, filtersTitle: 'Hosté, čas a datum', forExperience: (title) => `Pro ${title}.`, chooseStart: 'Nejprve vyberte zážitek.',
  },
  ro: {
    select: 'Selectează', experience: 'Experiență', guests: 'Oaspeți', time: 'Ora', date: 'Data', ports: 'Porturi',
    chooseExperience: 'Alegeți o experiență', chooseExperienceHint: 'Selectați o experiență pentru a continua.', guestQuestion: 'Câți oaspeți?', decreaseGuests: 'Mai puțini oaspeți', increaseGuests: 'Mai mulți oaspeți', chooseTime: 'Alegeți ora', chooseDate: 'Alegeți data', portsTitle: 'Porturi și transfer', portsHint: 'Alegeți porturile de plecare și sosire și transferurile private.', continue: 'Continuă', back: 'Înapoi', review: 'Verifică rezumatul', noBoats: 'Nu sunt bărci disponibile pentru aceste filtre', reset: 'Resetează filtrele', showAll: 'Arată toate experiențele', formName: 'Cum vă numiți?', formPhone: 'Care este numărul de telefon?', formEmail: 'Care este adresa de e-mail?', formNotes: 'Aveți cereri speciale?', optional: 'Opțional', boats: 'Bărci', availabilityAria: 'Disponibilitatea experienței selectate', customizeExperience: (title) => `Personalizați "${title}"`, filtersTitle: 'Oaspeți, oră și dată', forExperience: (title) => `Pentru ${title}.`, chooseStart: 'Alegeți o experiență pentru a începe.',
  },
  tr: {
    select: 'Seç', experience: 'Deneyim', guests: 'Misafirler', time: 'Saat', date: 'Tarih', ports: 'Limanlar',
    chooseExperience: 'Bir deneyim seçin', chooseExperienceHint: 'Devam etmek için bir deneyim seçin.', guestQuestion: 'Kaç misafir?', decreaseGuests: 'Misafir azalt', increaseGuests: 'Misafir artır', chooseTime: 'Saat seçin', chooseDate: 'Tarih seçin', portsTitle: 'Limanlar ve transfer', portsHint: 'Kalkış ve varış limanlarını ve özel transferleri seçin.', continue: 'Devam et', back: 'Geri', review: 'Özeti gözden geçir', noBoats: 'Bu filtrelere uygun tekne yok', reset: 'Filtreleri sıfırla', showAll: 'Tüm deneyimleri göster', formName: 'Adınız nedir?', formPhone: 'Telefon numaranız nedir?', formEmail: 'E-posta adresiniz nedir?', formNotes: 'Özel bir isteğiniz var mı?', optional: 'İsteğe bağlı', boats: 'Tekneler', availabilityAria: 'Seçili deneyimin uygunluğu', customizeExperience: (title) => `"${title}" deneyimini özelleştirin`, filtersTitle: 'Misafirler, saat ve tarih', forExperience: (title) => `${title} için.`, chooseStart: 'Başlamak için bir deneyim seçin.',
  },
  ja: {
    select: '選択', experience: '体験', guests: '人数', time: '時間', date: '日付', ports: '港',
    chooseExperience: '体験を選択', chooseExperienceHint: '続行するには体験を選択してください。', guestQuestion: '参加人数は？', decreaseGuests: '人数を減らす', increaseGuests: '人数を増やす', chooseTime: '時間を選択', chooseDate: '日付を選択', portsTitle: '港と送迎', portsHint: '出発港、到着港、専用送迎を選択してください。', continue: '次へ', back: '戻る', review: '内容を確認', noBoats: '条件に合うボートがありません', reset: '条件をリセット', showAll: 'すべての体験を見る', formName: 'お名前は？', formPhone: '電話番号は？', formEmail: 'メールアドレスは？', formNotes: '特別なご要望は？', optional: '任意', boats: 'ボート', availabilityAria: '選択した体験の空き状況', customizeExperience: (title) => `「${title}」をカスタマイズ`, filtersTitle: '人数、時間、日付', forExperience: (title) => `${title}について。`, chooseStart: '最初に体験を選択してください。',
  },
  ko: {
    select: '선택', experience: '체험', guests: '인원', time: '시간', date: '날짜', ports: '항구',
    chooseExperience: '체험 선택', chooseExperienceHint: '계속하려면 체험을 선택하세요.', guestQuestion: '몇 명인가요?', decreaseGuests: '인원 줄이기', increaseGuests: '인원 늘리기', chooseTime: '시간 선택', chooseDate: '날짜 선택', portsTitle: '항구 및 이동', portsHint: '출발 항구, 도착 항구, 프라이빗 이동을 선택하세요.', continue: '계속', back: '뒤로', review: '요약 확인', noBoats: '조건에 맞는 보트가 없습니다', reset: '필터 초기화', showAll: '모든 체험 보기', formName: '성함을 알려주세요', formPhone: '전화번호는 무엇인가요?', formEmail: '이메일 주소는 무엇인가요?', formNotes: '특별 요청이 있나요?', optional: '선택 사항', boats: '보트', availabilityAria: '선택한 체험 예약 가능 여부', customizeExperience: (title) => `"${title}" 맞춤 설정`, filtersTitle: '인원, 시간, 날짜', forExperience: (title) => `${title} 선택.`, chooseStart: '먼저 체험을 선택하세요.',
  },
};

export const additionalBookingExperienceNotes = {
  pt: { aperitivoCalloutTitle: 'Aperitivo disponível apenas em alguns horários', aperitivoCalloutText: 'Apenas Pôr do sol + Aperitivo e Dia inteiro + Aperitivo incluem o Gourmet Sunset Cruise. Suplemento de €390.', earlyBirdLegend: 'Indica uma data com desconto de reserva antecipada.' },
  nl: { aperitivoCalloutTitle: 'Aperitivo alleen op geselecteerde tijden', aperitivoCalloutText: 'Alleen Zonsondergang + Aperitivo en Hele dag + Aperitivo bevatten de Gourmet Sunset Cruise. Toeslag €390.', earlyBirdLegend: 'Markeert een datum met vroegboekkorting.' },
  he: { aperitivoCalloutTitle: 'אפריטיף זמין רק בשעות נבחרות', aperitivoCalloutText: 'רק שקיעה + אפריטיף ויום מלא + אפריטיף כוללים את Gourmet Sunset Cruise. תוספת €390.', earlyBirdLegend: 'מסמן תאריך עם הנחת הזמנה מוקדמת.' },
  cs: { aperitivoCalloutTitle: 'Aperitivo jen ve vybraných časech', aperitivoCalloutText: 'Pouze Západ slunce + Aperitivo a Celý den + Aperitivo zahrnují Gourmet Sunset Cruise. Příplatek €390.', earlyBirdLegend: 'Označuje datum se slevou za včasnou rezervaci.' },
  ro: { aperitivoCalloutTitle: 'Aperitivo disponibil doar la anumite ore', aperitivoCalloutText: 'Doar Apus + Aperitivo și Zi întreagă + Aperitivo includ Gourmet Sunset Cruise. Supliment €390.', earlyBirdLegend: 'Indică o dată cu reducere pentru rezervare timpurie.' },
  tr: { aperitivoCalloutTitle: 'Aperitivo yalnızca belirli saatlerde', aperitivoCalloutText: 'Yalnızca Gün batımı + Aperitivo ve Tam gün + Aperitivo, Gourmet Sunset Cruise’u içerir. €390 ek ücret.', earlyBirdLegend: 'Erken rezervasyon indirimli tarihi gösterir.' },
  ja: { aperitivoCalloutTitle: 'アペリティーボは一部の時間帯のみ', aperitivoCalloutText: '「夕日＋アペリティーボ」と「終日＋アペリティーボ」のみGourmet Sunset Cruiseを含みます。追加€390。', earlyBirdLegend: '早期予約割引の対象日です。' },
  ko: { aperitivoCalloutTitle: '아페리티보는 일부 시간대에만 제공', aperitivoCalloutText: '선셋 + 아페리티보와 종일 + 아페리티보에만 Gourmet Sunset Cruise가 포함됩니다. 추가 €390.', earlyBirdLegend: '얼리버드 할인 날짜를 표시합니다.' },
};

export const additionalFooterUi = {
  pt: { tagline: 'Passeios privados de barco com skipper desde Génova pelo Golfo Paradiso e Golfo do Tigullio.', explore: 'Explorar', home: 'Início', book: 'Reservar', faq: 'Perguntas frequentes', policy: 'Política e condições', experiences: 'Experiências', areas: 'Onde navegamos', contact: 'Contactos', call: 'Ligar a Riccardo', whatsapp: 'Escrever no WhatsApp', email: 'Enviar e-mail', legalInfo: 'Sede em Génova (GE) - Operamos entre Génova e Portofino', taxId: 'IVA 03030880995', taxNote: 'Serviço prestado ao abrigo do regime fiscal italiano de taxa fixa nos termos da Lei n.º 190/2014, não sujeito a IVA.', copyright: '© 2026 Leggero Tours. Todos os direitos reservados.' },
  nl: { tagline: 'Privéboottochten met schipper vanuit Genua door Golfo Paradiso en de Golf van Tigullio.', explore: 'Ontdekken', home: 'Home', book: 'Boeken', faq: 'Veelgestelde vragen', policy: 'Beleid en voorwaarden', experiences: 'Ervaringen', areas: 'Waar we varen', contact: 'Contact', call: 'Bel Riccardo', whatsapp: 'Stuur een WhatsApp', email: 'Stuur een e-mail', legalInfo: 'Gevestigd in Genua (GE) - Actief tussen Genua en Portofino', taxId: 'Btw-nr. 03030880995', taxNote: 'Dienst geleverd onder de Italiaanse forfaitaire belastingregeling volgens Wet nr. 190/2014 en daarom niet onderworpen aan btw.', copyright: '© 2026 Leggero Tours. Alle rechten voorbehouden.' },
  he: { tagline: 'סיורי סירה פרטיים עם סקיפר מג׳נובה דרך מפרץ פרדיסו ומפרץ טיגוליו.', explore: 'גלו', home: 'דף הבית', book: 'הזמנה', faq: 'שאלות נפוצות', policy: 'מדיניות ותנאים', experiences: 'חוויות', areas: 'אזורי השיט', contact: 'יצירת קשר', call: 'התקשרו לריקרדו', whatsapp: 'כתבו ב-WhatsApp', email: 'שלחו דוא״ל', legalInfo: 'משרד בג׳נובה (GE) - פעילות בין ג׳נובה לפורטופינו', taxId: 'מס׳ מע״מ 03030880995', taxNote: 'השירות ניתן במסגרת משטר המס האיטלקי הקבוע לפי חוק 190/2014 ולכן אינו חייב במע״מ.', copyright: '© 2026 Leggero Tours. כל הזכויות שמורות.' },
  cs: { tagline: 'Soukromé plavby se skipperem z Janova přes Golfo Paradiso a záliv Tigullio.', explore: 'Objevovat', home: 'Domů', book: 'Rezervovat', faq: 'Časté otázky', policy: 'Podmínky', experiences: 'Zážitky', areas: 'Kde plujeme', contact: 'Kontakt', call: 'Zavolat Riccardovi', whatsapp: 'Napsat na WhatsApp', email: 'Poslat e-mail', legalInfo: 'Sídlo v Janově (GE) - Provoz mezi Janovem a Portofinem', taxId: 'DIČ 03030880995', taxNote: 'Služba je poskytována v italském paušálním daňovém režimu podle zákona č. 190/2014, a proto nepodléhá DPH.', copyright: '© 2026 Leggero Tours. Všechna práva vyhrazena.' },
  ro: { tagline: 'Tururi private cu barca și skipper din Genova prin Golfo Paradiso și Golful Tigullio.', explore: 'Explorează', home: 'Acasă', book: 'Rezervă', faq: 'Întrebări frecvente', policy: 'Politică și condiții', experiences: 'Experiențe', areas: 'Unde navigăm', contact: 'Contact', call: 'Sună-l pe Riccardo', whatsapp: 'Scrie pe WhatsApp', email: 'Trimite e-mail', legalInfo: 'Sediu în Genova (GE) - Operăm între Genova și Portofino', taxId: 'TVA 03030880995', taxNote: 'Serviciu prestat în regimul fiscal forfetar italian conform Legii nr. 190/2014 și, prin urmare, neimpozabil cu TVA.', copyright: '© 2026 Leggero Tours. Toate drepturile rezervate.' },
  tr: { tagline: 'Cenova’dan Golfo Paradiso ve Tigullio Körfezi boyunca kaptanlı özel tekne turları.', explore: 'Keşfet', home: 'Ana sayfa', book: 'Rezervasyon', faq: 'Sık sorulanlar', policy: 'Politika ve koşullar', experiences: 'Deneyimler', areas: 'Seyir bölgeleri', contact: 'İletişim', call: 'Riccardo’yu ara', whatsapp: 'WhatsApp’tan yaz', email: 'E-posta gönder', legalInfo: 'Merkez Cenova (GE) - Cenova ile Portofino arasında hizmet', taxId: 'KDV No. 03030880995', taxNote: 'Hizmet, 190/2014 sayılı Kanun uyarınca İtalya’nın sabit oranlı vergi rejimi kapsamında sağlanır ve KDV’ye tabi değildir.', copyright: '© 2026 Leggero Tours. Tüm hakları saklıdır.' },
  ja: { tagline: 'ジェノヴァ発、船長付きのプライベートボートツアー。ゴルフォ・パラディーゾとティグッリオ湾を巡ります。', explore: '見る', home: 'ホーム', book: '予約', faq: 'よくある質問', policy: '規約', experiences: '体験', areas: '航行エリア', contact: 'お問い合わせ', call: 'Riccardoに電話', whatsapp: 'WhatsAppで連絡', email: 'メールを送る', legalInfo: '拠点：ジェノヴァ（GE）- ジェノヴァ〜ポルトフィーノで運航', taxId: 'VAT番号 03030880995', taxNote: '本サービスはイタリア法190/2014に基づく定額税制の対象であり、VATは課税されません。', copyright: '© 2026 Leggero Tours. 無断転載を禁じます。' },
  ko: { tagline: '제노바에서 출발해 골포 파라디소와 티굴리오만을 운항하는 선장 동반 프라이빗 보트 투어.', explore: '둘러보기', home: '홈', book: '예약', faq: '자주 묻는 질문', policy: '정책 및 조건', experiences: '체험', areas: '운항 지역', contact: '문의', call: 'Riccardo에게 전화', whatsapp: 'WhatsApp 문의', email: '이메일 보내기', legalInfo: '제노바(GE) 소재 - 제노바와 포르토피노 사이 운항', taxId: 'VAT 번호 03030880995', taxNote: '본 서비스는 이탈리아 법률 190/2014에 따른 정액 과세 제도로 제공되며 VAT가 부과되지 않습니다.', copyright: '© 2026 Leggero Tours. 모든 권리 보유.' },
};

export const additionalSeoUi = {
  pt: { home: { title: 'Passeios Privados de Barco em Génova e Portofino | Leggero Tours', description: 'Passeios privados com skipper entre Génova, Camogli, San Fruttuoso e Portofino.' }, book: { title: 'Reserve um Passeio Privado de Barco | Leggero Tours', description: 'Escolha experiência, data, pessoas e porto para um passeio privado na costa da Ligúria.' } },
  nl: { home: { title: 'Privéboottochten Genua en Portofino | Leggero Tours', description: 'Privéboottochten met schipper tussen Genua, Camogli, San Fruttuoso en Portofino.' }, book: { title: 'Boek een Privéboottocht in Ligurië | Leggero Tours', description: 'Kies ervaring, datum, gasten en vertrekhaven voor je privéboottocht.' } },
  he: { home: { title: 'סיורי סירה פרטיים מג׳נובה לפורטופינו | Leggero Tours', description: 'סיורי סירה פרטיים עם סקיפר בין ג׳נובה, קמולי, סן פרוטואוזו ופורטופינו.' }, book: { title: 'הזמנת סיור סירה פרטי בליגוריה | Leggero Tours', description: 'בחרו חוויה, תאריך, מספר אורחים ונמל יציאה לסיור פרטי.' } },
  cs: { home: { title: 'Soukromé Plavby Janov a Portofino | Leggero Tours', description: 'Soukromé plavby se skipperem mezi Janovem, Camogli, San Fruttuoso a Portofinem.' }, book: { title: 'Rezervace Soukromé Plavby v Ligurii | Leggero Tours', description: 'Vyberte zážitek, datum, hosty a přístav pro soukromou plavbu.' } },
  ro: { home: { title: 'Tururi Private cu Barca Genova și Portofino | Leggero Tours', description: 'Tururi private cu skipper între Genova, Camogli, San Fruttuoso și Portofino.' }, book: { title: 'Rezervă un Tur Privat cu Barca | Leggero Tours', description: 'Alege experiența, data, oaspeții și portul pentru un tur privat în Liguria.' } },
  tr: { home: { title: 'Cenova ve Portofino Özel Tekne Turları | Leggero Tours', description: 'Cenova, Camogli, San Fruttuoso ve Portofino arasında kaptanlı özel tekne turları.' }, book: { title: 'Ligurya’da Özel Tekne Turu Ayırtın | Leggero Tours', description: 'Özel turunuz için deneyim, tarih, misafir sayısı ve limanı seçin.' } },
  ja: { home: { title: 'ジェノヴァ・ポルトフィーノのプライベートボートツアー | Leggero Tours', description: 'ジェノヴァ、カモーリ、サン・フルットゥオーゾ、ポルトフィーノを巡る船長付き貸切ツアー。' }, book: { title: 'リグーリアのプライベートボートツアー予約 | Leggero Tours', description: '体験、日付、人数、出発港を選んで貸切ツアーを予約。' } },
  ko: { home: { title: '제노바·포르토피노 프라이빗 보트 투어 | Leggero Tours', description: '제노바, 카몰리, 산 프루투오소, 포르토피노를 잇는 선장 동반 프라이빗 투어.' }, book: { title: '리구리아 프라이빗 보트 투어 예약 | Leggero Tours', description: '체험, 날짜, 인원, 출발 항구를 선택해 프라이빗 투어를 예약하세요.' } },
};

export const additionalExperienceUi = {
  pt: { details: 'Detalhes da experiência', learnMore: 'Saber mais', book: 'Reservar agora', contact: 'Contacte-nos', request: 'Pedido no WhatsApp', location: 'Ver localização', important: 'Nota importante', multiplier: 'Multiplicador', charter: 'Tipo de charter', included: 'Incluído', previous: 'Paragem anterior', next: 'Paragem seguinte', show: 'Mostrar paragem', transcript: 'Descrição do mapa', stop: 'Paragem', map: 'Abrir mapa', sources: 'Fontes' },
  nl: { details: 'Ervaringsdetails', learnMore: 'Meer info', book: 'Nu boeken', contact: 'Contact', request: 'Aanvraag via WhatsApp', location: 'Bekijk locatie', important: 'Belangrijke opmerking', multiplier: 'Vermenigvuldiger', charter: 'Type charter', included: 'Inbegrepen', previous: 'Vorige stop', next: 'Volgende stop', show: 'Stop tonen', transcript: 'Kaartbeschrijving', stop: 'Stop', map: 'Kaart openen', sources: 'Bronnen' },
  he: { details: 'פרטי החוויה', learnMore: 'לגלות עוד', book: 'הזמנה עכשיו', contact: 'יצירת קשר', request: 'בקשה ב-WhatsApp', location: 'צפייה במיקום', important: 'הערה חשובה', multiplier: 'מכפיל', charter: 'סוג השכרה', included: 'כלול', previous: 'התחנה הקודמת', next: 'התחנה הבאה', show: 'הצגת תחנה', transcript: 'תיאור המפה', stop: 'תחנה', map: 'פתיחת מפה', sources: 'מקורות' },
  cs: { details: 'Detaily zážitku', learnMore: 'Zjistit více', book: 'Rezervovat', contact: 'Kontakt', request: 'Dotaz přes WhatsApp', location: 'Zobrazit místo', important: 'Důležitá poznámka', multiplier: 'Násobitel', charter: 'Typ charteru', included: 'Zahrnuto', previous: 'Předchozí zastávka', next: 'Další zastávka', show: 'Zobrazit zastávku', transcript: 'Popis mapy', stop: 'Zastávka', map: 'Otevřít mapu', sources: 'Zdroje' },
  ro: { details: 'Detaliile experienței', learnMore: 'Află mai mult', book: 'Rezervă acum', contact: 'Contactați-ne', request: 'Cerere pe WhatsApp', location: 'Vezi locația', important: 'Notă importantă', multiplier: 'Multiplicator', charter: 'Tip charter', included: 'Inclus', previous: 'Oprirea anterioară', next: 'Oprirea următoare', show: 'Arată oprirea', transcript: 'Descrierea hărții', stop: 'Oprire', map: 'Deschide harta', sources: 'Surse' },
  tr: { details: 'Deneyim ayrıntıları', learnMore: 'Daha fazla', book: 'Şimdi ayırt', contact: 'Bize ulaşın', request: 'WhatsApp’tan talep', location: 'Konumu gör', important: 'Önemli not', multiplier: 'Çarpan', charter: 'Tur türü', included: 'Dahil', previous: 'Önceki durak', next: 'Sonraki durak', show: 'Durağı göster', transcript: 'Harita açıklaması', stop: 'Durak', map: 'Haritayı aç', sources: 'Kaynaklar' },
  ja: { details: '体験の詳細', learnMore: '詳しく見る', book: '今すぐ予約', contact: 'お問い合わせ', request: 'WhatsAppで相談', location: '場所を見る', important: '重要事項', multiplier: '倍率', charter: 'チャーター種別', included: '含まれるもの', previous: '前の停泊地', next: '次の停泊地', show: '停泊地を表示', transcript: '地図の説明', stop: '停泊地', map: '地図を開く', sources: '出典' },
  ko: { details: '체험 상세', learnMore: '더 알아보기', book: '지금 예약', contact: '문의하기', request: 'WhatsApp 문의', location: '위치 보기', important: '중요 안내', multiplier: '배수', charter: '차터 유형', included: '포함 사항', previous: '이전 기항지', next: '다음 기항지', show: '기항지 표시', transcript: '지도 설명', stop: '기항지', map: '지도 열기', sources: '출처' },
};