const ui = {
  it: { details: 'Dettagli esperienza', book: 'Prenota ora', contact: 'Contattaci', request: 'Richiesta su WhatsApp', location: 'Scopri la location', important: 'Nota importante', multiplier: 'Moltiplicatore', charter: 'Tipologia charter', included: 'Incluso', previous: 'Tappa precedente', next: 'Tappa successiva', show: 'Mostra tappa', transcript: 'Trascrizione mappa', stop: 'Tappa', map: 'Apri mappa', sources: 'Fonti' },
  en: { details: 'Experience details', book: 'Book now', contact: 'Contact us', request: 'Request on WhatsApp', location: 'Discover the location', important: 'Important note', multiplier: 'Multiplier', charter: 'Charter type', included: 'Included', previous: 'Previous stop', next: 'Next stop', show: 'Show stop', transcript: 'Map transcript', stop: 'Stop', map: 'Open map', sources: 'Sources' },
  de: { details: 'Erlebnisdetails', book: 'Jetzt buchen', contact: 'Kontakt', request: 'Anfrage per WhatsApp', location: 'Ort ansehen', important: 'Wichtiger Hinweis', multiplier: 'Multiplikator', charter: 'Charterart', included: 'Inklusive', previous: 'Vorheriger Halt', next: 'Nächster Halt', show: 'Halt anzeigen', transcript: 'Kartenbeschreibung', stop: 'Halt', map: 'Karte öffnen', sources: 'Quellen' },
  es: { details: 'Detalles de la experiencia', book: 'Reservar ahora', contact: 'Contactar', request: 'Consultar por WhatsApp', location: 'Ver ubicación', important: 'Nota importante', multiplier: 'Multiplicador', charter: 'Tipo de chárter', included: 'Incluido', previous: 'Parada anterior', next: 'Siguiente parada', show: 'Mostrar parada', transcript: 'Descripción del mapa', stop: 'Parada', map: 'Abrir mapa', sources: 'Fuentes' },
  fr: { details: 'Détails de l’expérience', book: 'Réserver', contact: 'Nous contacter', request: 'Demande sur WhatsApp', location: 'Voir le lieu', important: 'Note importante', multiplier: 'Multiplicateur', charter: 'Type de charter', included: 'Inclus', previous: 'Étape précédente', next: 'Étape suivante', show: 'Afficher l’étape', transcript: 'Description de la carte', stop: 'Étape', map: 'Ouvrir la carte', sources: 'Sources' },
  ar: { details: 'تفاصيل التجربة', book: 'احجز الآن', contact: 'تواصل معنا', request: 'طلب عبر واتساب', location: 'اكتشف الموقع', important: 'ملاحظة مهمة', multiplier: 'المعامل', charter: 'نوع الرحلة', included: 'مشمول', previous: 'المحطة السابقة', next: 'المحطة التالية', show: 'عرض المحطة', transcript: 'وصف الخريطة', stop: 'المحطة', map: 'فتح الخريطة', sources: 'المصادر' },
  zh: { details: '体验详情', book: '立即预订', contact: '联系我们', request: '通过 WhatsApp 咨询', location: '查看位置', important: '重要提示', multiplier: '系数', charter: '包船类型', included: '已包含', previous: '上一站', next: '下一站', show: '显示停靠点', transcript: '地图说明', stop: '停靠点', map: '打开地图', sources: '来源' },
  pl: { details: 'Szczegóły atrakcji', book: 'Zarezerwuj', contact: 'Skontaktuj się', request: 'Zapytaj przez WhatsApp', location: 'Zobacz lokalizację', important: 'Ważna informacja', multiplier: 'Mnożnik', charter: 'Rodzaj czarteru', included: 'W cenie', previous: 'Poprzedni przystanek', next: 'Następny przystanek', show: 'Pokaż przystanek', transcript: 'Opis mapy', stop: 'Przystanek', map: 'Otwórz mapę', sources: 'Źródła' },
  ru: { details: 'Детали программы', book: 'Забронировать', contact: 'Связаться', request: 'Запрос в WhatsApp', location: 'Открыть место', important: 'Важная информация', multiplier: 'Коэффициент', charter: 'Тип чартера', included: 'Включено', previous: 'Предыдущая остановка', next: 'Следующая остановка', show: 'Показать остановку', transcript: 'Описание карты', stop: 'Остановка', map: 'Открыть карту', sources: 'Источники' },
  uk: { details: 'Деталі програми', book: 'Забронювати', contact: 'Звʼязатися', request: 'Запит у WhatsApp', location: 'Відкрити місце', important: 'Важлива інформація', multiplier: 'Коефіцієнт', charter: 'Тип чартеру', included: 'Включено', previous: 'Попередня зупинка', next: 'Наступна зупинка', show: 'Показати зупинку', transcript: 'Опис мапи', stop: 'Зупинка', map: 'Відкрити мапу', sources: 'Джерела' },
};

export function getExperienceUi(lang) {
  return ui[lang] || ui.en;
}
